<template><h2 id="realm-swiftui" tabindex="-1"><a class="header-anchor" href="#realm-swiftui" aria-hidden="true">#</a> Realm + SwiftUI</h2>
<p>Realm は SwiftUI を公式サポートしていないのでいろいろ対応が必要になりますが、その一つがデータ更新時にビューの再レンダリングに対応していないことが挙げられます。</p>
<p>また、データ削除でクラッシュする<a href="https://tkgstrator.work/posts/2021/05/24/realmrelation.html" target="_blank" rel="noopener noreferrer">Realm でレコードを削除するとクラッシュする問題
<OutboundLink/></a>もあるので、こちらにも目を通しておいて下さい。</p>
<h2 id="再レンダリングの方法" tabindex="-1"><a class="header-anchor" href="#再レンダリングの方法" aria-hidden="true">#</a> 再レンダリングの方法</h2>
<p>以下は再レンダリングを実行するためのテンプレートである。頻繁に使うので覚えておいたほうが良い。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">Combine</span>
<span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">RealmSwift</span>

<span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">!</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">class</span> <span class="token class-name">RealmCoopResult</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> goldenEggs <span class="token operator">=</span> <span class="token builtin">RealmOptional</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> powerEggs <span class="token operator">=</span> <span class="token builtin">RealmOptional</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>goldenEggs<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span><span class="token punctuation">,</span> powerEggs<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>goldenEggs<span class="token punctuation">.</span>value <span class="token operator">=</span> goldenEggs
        <span class="token keyword">self</span><span class="token punctuation">.</span>powerEggs<span class="token punctuation">.</span>value <span class="token operator">=</span> powerEggs
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token comment">// 最初の一回しか呼ばれない</span>
    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// 最初の一回しか呼ばれない</span>
        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            <span class="token comment">// データ変更が起こったときに実行される</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br></div></div><p>このコードの場合<code>objectWillChange.send()</code>で強制再レンダリングがかかるので変数は<code>@Published</code>属性を付けなくても良いことに注意。</p>
<div class="custom-container warning"><p class="custom-container-title">Realm インスタンスの呼び出し方</p>
<p>今回のテンプレートでは<code>let realm = try! Realm()</code>で呼び出しているが、この書き方だとマイグレーションが必要なときなどに必ずクラッシュしてしまう。</p>
<p>より柔軟な書き方については別の記事で解説予定。</p>
</div>
<p>あと、データの反映を全てのビューで受け取れるように<code>@EnvironmentObject</code>を設定する必要がある。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>@main
<span class="token keyword">struct</span> <span class="token builtin">RealmRelationApp</span><span class="token punctuation">:</span> <span class="token builtin">App</span> <span class="token punctuation">{</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">Scene</span> <span class="token punctuation">{</span>
        <span class="token builtin">WindowGroup</span> <span class="token punctuation">{</span>
            <span class="token function">ContentView</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">environmentObject</span><span class="token punctuation">(</span><span class="token function">Tkgstrator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 追加</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>このようにルートビューに<code>@EnviromentObject</code>を読み込むように設定する。これで、全てのビューで<code>Tkgstrator</code>クラスのデータにアクセスできる。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// ContentView.siwft</span>
<span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">EnvironmentObject</span> <span class="token keyword">var</span> data<span class="token punctuation">:</span> <span class="token builtin">Tkgstrator</span> <span class="token comment">// EnvironmentObjectを利用することを明記</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">NavigationView</span> <span class="token punctuation">{</span>
            <span class="token builtin">Form</span> <span class="token punctuation">{</span>
                <span class="token function">NavigationLink</span><span class="token punctuation">(</span>destination<span class="token punctuation">:</span> resultLists<span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"RESULTS"</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
                <span class="token function">NavigationLink</span><span class="token punctuation">(</span>destination<span class="token punctuation">:</span> settingMenu<span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"SETTING"</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> resultLists<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">addData</span><span class="token punctuation">(</span>num<span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"ADD DATA"</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token function">ForEach</span><span class="token punctuation">(</span>data<span class="token punctuation">.</span>results<span class="token punctuation">,</span> id<span class="token punctuation">:</span>\<span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> result <span class="token keyword">in</span>
                <span class="token builtin">HStack</span> <span class="token punctuation">{</span>
                    <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>result<span class="token punctuation">.</span>goldenEggs<span class="token punctuation">.</span>value <span class="token operator">?</span><span class="token operator">?</span> <span class="token number">0</span><span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
                    <span class="token function">Spacer</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                    <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>result<span class="token punctuation">.</span>powerEggs<span class="token punctuation">.</span>value <span class="token operator">?</span><span class="token operator">?</span> <span class="token number">0</span><span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> settingMenu<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token builtin">HStack</span> <span class="token punctuation">{</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"RESULTS NUM"</span><span class="token punctuation">)</span>
                <span class="token function">Spacer</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>data<span class="token punctuation">.</span>results<span class="token punctuation">.</span><span class="token builtin">count</span><span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">addData</span><span class="token punctuation">(</span>num<span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"ADD DATA"</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">deleteAll</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"DELETE ALL"</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">addData</span><span class="token punctuation">(</span>num<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        autoreleasepool <span class="token punctuation">{</span>
            realm<span class="token punctuation">.</span><span class="token function">beginWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token keyword">for</span> <span class="token number">_</span> <span class="token keyword">in</span> <span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token operator">&lt;</span> num <span class="token punctuation">{</span>
                realm<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> <span class="token function">RealmCoopResult</span><span class="token punctuation">(</span>goldenEggs<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token number">69</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token operator">&lt;</span> <span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">,</span> powerEggs<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token number">3000</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token operator">&lt;</span> <span class="token number">5000</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span><span class="token function">commitWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">deleteAll</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        autoreleasepool <span class="token punctuation">{</span>
            realm<span class="token punctuation">.</span><span class="token function">beginWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            realm<span class="token punctuation">.</span><span class="token function">deleteAll</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span><span class="token function">commitWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br></div></div><h2 id="observableobject-の書き方" tabindex="-1"><a class="header-anchor" href="#observableobject-の書き方" aria-hidden="true">#</a> OBservableObject の書き方</h2>
<p>さて、ここまでで<code>RealmSwift.Results</code>を常に最新のものをとってくることができた。</p>
<div class="custom-container tip"><p class="custom-container-title">初期化は一回しか行われていないが...</p>
<p><code>results</code>への代入は一回しか行われていないので値が更新されないように思うかもしれないが、<code>realm</code>のインスタンスの内部状態は常に最新のものに更新されるので（計算プロパティのようなものと思えば良い）、<code>results</code>のプロパティを参照すれば常に最新のデータが取得できる。</p>
</div>
<p>データベースを運用していく上では単に全てのリザルトだけでなくさまざまなデータを計算してその結果を返してほしいのだが、それをどうやってコーディングすればいいかを考える。</p>
<p>例えば、それぞれの平均を求めたいとしよう。Realm には平均を返す<code>average(ofProperty: String)</code>というものがあるのでこれを利用する。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動かないコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>
    <span class="token keyword">let</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        avgGoldenEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span> <span class="token comment">// この時点で値が決まっている</span>
        avgPowerEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span> <span class="token comment">// この時点で値が決まっている</span>

        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><p>一見すると上のコードで動作しそうな気がするが、これは正しく動かない。というのも、<code>avgGoldenEggs</code>というのは<code>Double?</code>型の変数であり、<code>realm</code>のインスタンスの内部状態に依存しないためだ。つまり、イニシャライザでプロパティに代入した瞬間に値が決まってしまい、<code>objectWillChange.send()</code>が呼ばれてもデータが更新されない。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動かないコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        avgGoldenEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span> <span class="token comment">// この時点で値が決まっている</span>
        avgPowerEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span> <span class="token comment">// この時点で値が決まっている</span>

        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><p>それは<code>@Published</code>をつけても同様のことがいえる。そもそも、<code>@Published</code>自体が「そのプロパティのデータが更新されたときにビューを再レンダリングする」という効果しか持たないので、<code>objectWillChange.send()</code>を使うのであれば不要である。</p>
<p>これも、何回実行しても最初のイニシャライザで設定した値から変わらないのでやはり再レンダリングはできない。</p>
<h2 id="読み込み時に計算するコード" tabindex="-1"><a class="header-anchor" href="#読み込み時に計算するコード" aria-hidden="true">#</a> 読み込み時に計算するコード</h2>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動作するコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span> <span class="token punctuation">{</span>
        results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span> <span class="token punctuation">{</span>
        results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><p>そのためには、例えば変数を計算プロパティにするという方法が考えられる。これは<code>results</code>は常に最新のデータを取得するので呼び出すごとに結果が変わり、そのためデータを追加すれば正しくビューの再レンダリングがかかり平均のデータも更新される。</p>
<h3 id="データを毎回代入するコード" tabindex="-1"><a class="header-anchor" href="#データを毎回代入するコード" aria-hidden="true">#</a> データを毎回代入するコード</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動くコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>
    <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            avgGoldenEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span>
            avgPowerEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p>このようにデータベース更新時に毎回代入し直すようなコードでも正しく動作する。</p>
<h3 id="データを毎回代入するコード-1" tabindex="-1"><a class="header-anchor" href="#データを毎回代入するコード-1" aria-hidden="true">#</a> データを毎回代入するコード</h3>
<p><code>objectWillChange.send()</code>を使わず、<code>@Published</code>を利用する方法でも良い。</p>
<p>が、何度も<code>@Published</code>を書くことになるので、個人的には一回だけ<code>objectWillChange.send()</code>を使うほうが楽そうな気はする。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動くコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    @<span class="token builtin">Published</span> <span class="token keyword">var</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            avgGoldenEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span>
            avgPowerEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h2 id="現時点でオススメのコード" tabindex="-1"><a class="header-anchor" href="#現時点でオススメのコード" aria-hidden="true">#</a> 現時点でオススメのコード</h2>
<h3 id="計算内容が重い場合" tabindex="-1"><a class="header-anchor" href="#計算内容が重い場合" aria-hidden="true">#</a> 計算内容が重い場合</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>
    <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            avgGoldenEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span>
            avgPowerEggs <span class="token operator">=</span> results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span>
            objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p>このコードの注意すべき点はデータベースに何らかの変更があったときに、毎回クロージャ内の計算が実行されてしまうということである。</p>
<p>つまり、100 件のデータ書き込みを 1 件ずつ行っていると毎回計算処理が発生して非常にパフォーマンスがよろしくない。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>realm<span class="token punctuation">.</span><span class="token function">beginWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">for</span> result <span class="token keyword">in</span> results <span class="token punctuation">{</span>
    <span class="token comment">// データ書き込み（実際には書き込まれていない）</span>
<span class="token punctuation">}</span>
<span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span><span class="token function">commitWrite</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// ここで全件書き込み</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>のように 100 件同時書き込みをするようにコーディングすること。こうすれば 100 件データが追加されたあとでしか計算処理が発生しない。</p>
<h3 id="計算内容が軽い場合" tabindex="-1"><a class="header-anchor" href="#計算内容が軽い場合" aria-hidden="true">#</a> 計算内容が軽い場合</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 正しく動作するコード</span>
<span class="token keyword">class</span> <span class="token class-name">Tkgstrator</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>

    <span class="token keyword">let</span> results<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">RealmCoopResult</span><span class="token operator">></span> <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">RealmCoopResult</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> avgGoldenEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span> <span class="token punctuation">{</span>
        results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"goldenEggs"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">var</span> avgPowerEggs<span class="token punctuation">:</span> <span class="token builtin">Double</span><span class="token operator">?</span> <span class="token punctuation">{</span>
        results<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>ofProperty<span class="token punctuation">:</span> <span class="token string">"powerEggs"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// メモリリークを防ぐために弱参照を用いる</span>
        token <span class="token operator">=</span> results<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">weak</span> <span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            <span class="token keyword">self</span><span class="token operator">?</span><span class="token punctuation">.</span>objectWillChange<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><p>現時点ではこのコードが一番オススメかなあという気がしている。なんといっても、イニシャライザが非常に簡単にかけることが大きい。</p>
<p>スパゲッティコードになることを防ぎやすく、わかりやすさでは一番の気がしている。</p>
<div class="custom-container warning"><p class="custom-container-title">注意点</p>
<p>ただし、どちらの場合もイニシャライザやクロージャ内や計算プロパティ内に重い処理を書いているとアプリがフリーズしたような状態になってしまうので、それを防ぐためには<code>DispatchQueue</code>を使ってメインスレッド以外で実行する必要が出てくる。</p>
<p>このとき、全部の計算プロパティをいちいち別スレッドで実行するのもめんどくさいので、重い処理が多いときは前者の書き方のほうが良いかもしれない。</p>
</div>
<p>というわけで、SwiftUI と Realm の組み合わせの仕方について学びました。</p>
<p>これを使ってアプリ開発を勧めていきたいと思いました、まる。</p>
<p>記事は以上。</p>
</template>
