<template><h2 id="swiftui-でタップイベントを取得する" tabindex="-1"><a class="header-anchor" href="#swiftui-でタップイベントを取得する" aria-hidden="true">#</a> SwiftUI でタップイベントを取得する</h2>
<p>SwiftUI でタップされたイベントを取得するのであれば適当な View に<a href="https://developer.apple.com/documentation/swiftui/tapgesture" target="_blank" rel="noopener noreferrer"><code>onTapGesture()</code><OutboundLink/></a>をつければよいのだが<code>ontapGesture()</code>はタップされたときにクロージャ内の処理を実行してくれるが、そのときにどこの座標がタップされたのかは教えてくれない。</p>
<p>例えばお絵かきアプリをリリースしたいとして、タップした場所に円を表示するようなコードを書こうとしたら必ず「タップした場所」の情報が必要になる。</p>
<p>お絵かきアプリだとキャンバスの拡大縮小があったりして「画面の座標」と「キャンバスの座標」の二つを考えなければならず、めちゃくちゃややこしいことになりそうなのだが、今回はそういうことは考えず単に画面のどこがタップされたかを知りたいとしよう。</p>
<h2 id="タップイベント三兄弟" tabindex="-1"><a class="header-anchor" href="#タップイベント三兄弟" aria-hidden="true">#</a> タップイベント三兄弟</h2>
<p><a href="https://qiita.com/Kyome/items/d86cefa9dbd7bd2d7cf0" target="_blank" rel="noopener noreferrer">Swift：タッチイベントの際にタッチした座標を取得する方法二通り<OutboundLink/></a>によれば Swift では二通りの方法でタップされた座標を取得する方法があるらしい。</p>
<p>検索をかけた段階で SwiftUI ではなく Swift の情報がでてくる時点でちょっと嫌な予感はしたりする。</p>
<h2 id="暫定的な対応" tabindex="-1"><a class="header-anchor" href="#暫定的な対応" aria-hidden="true">#</a> 暫定的な対応</h2>
<p><a href="https://stackoverflow.com/questions/56513942/how-to-detect-a-tap-gesture-location-in-swiftui" target="_blank" rel="noopener noreferrer">How to detect a tap gesture location in SwiftUI?<OutboundLink/></a>に解決策が載っていて、<code>TapGesture</code>を使うことでなんと SwiftUI ネイティブに解決できるという。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Color</span><span class="token punctuation">.</span>gray<span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span><span class="token number">0.5</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">gesture</span><span class="token punctuation">(</span><span class="token function">DragGesture</span><span class="token punctuation">(</span>minimumDistance<span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">onEnded</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token punctuation">(</span>value<span class="token punctuation">)</span> <span class="token keyword">in</span>
                <span class="token function">print</span><span class="token punctuation">(</span>value<span class="token punctuation">.</span>location<span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>いろいろ回答が載っているが、これが最もシンプルに動く。これが<code>DragGesture</code>を使っているが<code>minumumDistance</code>が 0 なので実質タップした位置の座標が取得できる。注意点としては<code>value</code>に入っているのは指を離した時点での座標なので、厳密に最初にタップした位置を取得できるわけではない。</p>
<p>まあ、それはそういうものだと割り切ってしまおう。</p>
<h3 id="objective-c-を利用した解決策" tabindex="-1"><a class="header-anchor" href="#objective-c-を利用した解決策" aria-hidden="true">#</a> Objective-C を利用した解決策</h3>
<p>Objective-C を使えばより厳密にタップ位置を取得できる。このコードは<code>UITapGestureRecognizer</code>を利用しているので純粋にタップした位置しか取得しない。</p>
<p>タップ以外のジェスチャーは認識しないというのも強みと言えるだろう。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Color</span><span class="token punctuation">.</span>gray<span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span><span class="token number">0.5</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token function">Background</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">struct</span> <span class="token builtin">Background</span><span class="token punctuation">:</span> <span class="token builtin">UIViewRepresentable</span> <span class="token punctuation">{</span>
    <span class="token keyword">func</span> <span class="token function">makeUIView</span><span class="token punctuation">(</span>context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">UIView</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> uiview <span class="token operator">=</span> <span class="token function">UIView</span><span class="token punctuation">(</span>frame<span class="token punctuation">:</span> <span class="token punctuation">.</span>zero<span class="token punctuation">)</span>
        <span class="token keyword">let</span> gesture <span class="token operator">=</span> <span class="token function">UITapGestureRecognizer</span><span class="token punctuation">(</span>
            target<span class="token punctuation">:</span> context<span class="token punctuation">.</span>coordinator<span class="token punctuation">,</span>
            action<span class="token punctuation">:</span> #<span class="token function">selector</span><span class="token punctuation">(</span><span class="token builtin">Coordinator</span><span class="token punctuation">.</span>tappedGesture<span class="token punctuation">)</span><span class="token punctuation">)</span>
        uiview<span class="token punctuation">.</span><span class="token function">addGestureRecognizer</span><span class="token punctuation">(</span>gesture<span class="token punctuation">)</span>
        <span class="token keyword">return</span> uiview
    <span class="token punctuation">}</span>

    <span class="token keyword">class</span> <span class="token class-name">Coordinator</span><span class="token punctuation">:</span> <span class="token builtin">NSObject</span> <span class="token punctuation">{</span>
        <span class="token atrule">@objc</span> <span class="token keyword">func</span> <span class="token function">tappedGesture</span><span class="token punctuation">(</span>gesture<span class="token punctuation">:</span> <span class="token builtin">UITapGestureRecognizer</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">let</span> point <span class="token operator">=</span> gesture<span class="token punctuation">.</span><span class="token function">location</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> gesture<span class="token punctuation">.</span>view<span class="token punctuation">)</span>
            <span class="token comment">// TapGesture</span>
            <span class="token function">print</span><span class="token punctuation">(</span>point<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">makeCoordinator</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Coordinator</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">Coordinator</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">updateUIView</span><span class="token punctuation">(</span><span class="token number">_</span> uiView<span class="token punctuation">:</span> <span class="token builtin">UIView</span><span class="token punctuation">,</span> context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br></div></div><p>このコードは<code>Background</code>のビューで全てを完結させているが、親ビューで処理を行いたい場合もある。</p>
<h3 id="クロージャで親-view-に値を返す場合" tabindex="-1"><a class="header-anchor" href="#クロージャで親-view-に値を返す場合" aria-hidden="true">#</a> クロージャで親 View に値を返す場合</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Color</span><span class="token punctuation">.</span>gray<span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span><span class="token number">0.5</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token builtin">Background</span> <span class="token punctuation">{</span> location <span class="token keyword">in</span>
                <span class="token comment">// TapGesture</span>
                <span class="token function">print</span><span class="token punctuation">(</span>location<span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">struct</span> <span class="token builtin">Background</span><span class="token punctuation">:</span> <span class="token builtin">UIViewRepresentable</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> tappedCallback<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span>

    <span class="token keyword">func</span> <span class="token function">makeUIView</span><span class="token punctuation">(</span>context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">UIView</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> uiview <span class="token operator">=</span> <span class="token function">UIView</span><span class="token punctuation">(</span>frame<span class="token punctuation">:</span> <span class="token punctuation">.</span>zero<span class="token punctuation">)</span>
        <span class="token keyword">let</span> gesture <span class="token operator">=</span> <span class="token function">UITapGestureRecognizer</span><span class="token punctuation">(</span>
            target<span class="token punctuation">:</span> context<span class="token punctuation">.</span>coordinator<span class="token punctuation">,</span>
            action<span class="token punctuation">:</span> #<span class="token function">selector</span><span class="token punctuation">(</span><span class="token builtin">Coordinator</span><span class="token punctuation">.</span>tapped<span class="token punctuation">)</span><span class="token punctuation">)</span>
        uiview<span class="token punctuation">.</span><span class="token function">addGestureRecognizer</span><span class="token punctuation">(</span>gesture<span class="token punctuation">)</span>
        <span class="token keyword">return</span> uiview
    <span class="token punctuation">}</span>

    <span class="token keyword">class</span> <span class="token class-name">Coordinator</span><span class="token punctuation">:</span> <span class="token builtin">NSObject</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> tappedCallback<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span>

        <span class="token keyword">init</span><span class="token punctuation">(</span>tappedCallback<span class="token punctuation">:</span> @escaping <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">self</span><span class="token punctuation">.</span>tappedCallback <span class="token operator">=</span> tappedCallback
        <span class="token punctuation">}</span>

        <span class="token atrule">@objc</span> <span class="token keyword">func</span> <span class="token function">tapped</span><span class="token punctuation">(</span>gesture<span class="token punctuation">:</span><span class="token builtin">UITapGestureRecognizer</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">let</span> point <span class="token operator">=</span> gesture<span class="token punctuation">.</span><span class="token function">location</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> gesture<span class="token punctuation">.</span>view<span class="token punctuation">)</span>
            <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token function">tappedCallback</span><span class="token punctuation">(</span>point<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">makeCoordinator</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Background</span><span class="token punctuation">.</span><span class="token builtin">Coordinator</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">Coordinator</span><span class="token punctuation">(</span>tappedCallback<span class="token punctuation">:</span><span class="token keyword">self</span><span class="token punctuation">.</span>tappedCallback<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">updateUIView</span><span class="token punctuation">(</span><span class="token number">_</span> uiView<span class="token punctuation">:</span> <span class="token builtin">UIView</span><span class="token punctuation">,</span> context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br></div></div><h2 id="ガチホコカウントビューワ" tabindex="-1"><a class="header-anchor" href="#ガチホコカウントビューワ" aria-hidden="true">#</a> ガチホコカウントビューワ</h2>
<p>ガチホコカウントビューワではマップ画像をタップして、その位置でのカウントを表示するようなアプリにしたい。</p>
<p>ただ、どこをタップしかわからないのでは困るので、最後にタップした位置に何かしらのマークを付けておき、その位置でのカウントを表示するようにしたい。</p>
<p>そこで、先程のコードを修正して最後にタップした位置に円のオブジェクトを表示できるようにしてみる。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> location<span class="token punctuation">:</span> <span class="token builtin">CGPoint</span><span class="token operator">?</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Color</span><span class="token punctuation">.</span>clear
            <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token builtin">Background</span> <span class="token punctuation">{</span> location <span class="token keyword">in</span>
                <span class="token keyword">self</span><span class="token punctuation">.</span>location <span class="token operator">=</span> location
            <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span>locationIcon<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> locationIcon<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> location <span class="token operator">=</span> <span class="token keyword">self</span><span class="token punctuation">.</span>location <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token function">AnyView</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>blue<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">30</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">position</span><span class="token punctuation">(</span>x<span class="token punctuation">:</span> location<span class="token punctuation">.</span>x<span class="token punctuation">,</span> y<span class="token punctuation">:</span> location<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token function">AnyView</span><span class="token punctuation">(</span><span class="token function">EmptyView</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><p>コードとしては極めて単純明快で、単にタップしたときに取得した位置を<code>@State</code>に保存しておくだけだ。<code>@State</code>は値が変わったときにビューの再レンダリングが行われるので、画像のどこかをタップすれば(画像は何でもいいので各自用意してほしい)その位置に青い円が表示されるというわけである。</p>
<h3 id="ドラッグにも対応したい" tabindex="-1"><a class="header-anchor" href="#ドラッグにも対応したい" aria-hidden="true">#</a> ドラッグにも対応したい</h3>
<p>が、実際に使ってみるとこれはひどく使い勝手が悪いことがわかる。</p>
<p>位置の細かい調整をしたいときはタップ判定よりもむしろドラッグ判定の方が便利なのだ。よって、画面をタップしてなぞっているときは指の位置に合わせて円がどんどん動いてくるようなシステムの方が望ましいのである。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">Background</span><span class="token punctuation">:</span> <span class="token builtin">UIViewRepresentable</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> tappedCallback<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span>

    <span class="token keyword">func</span> <span class="token function">makeUIView</span><span class="token punctuation">(</span>context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">UIView</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> uiview <span class="token operator">=</span> <span class="token function">UIView</span><span class="token punctuation">(</span>frame<span class="token punctuation">:</span> <span class="token punctuation">.</span>zero<span class="token punctuation">)</span>
        <span class="token keyword">let</span> gesture <span class="token operator">=</span> <span class="token function">UIPanGestureRecognizer</span><span class="token punctuation">(</span>
            target<span class="token punctuation">:</span> context<span class="token punctuation">.</span>coordinator<span class="token punctuation">,</span>
            action<span class="token punctuation">:</span> #<span class="token function">selector</span><span class="token punctuation">(</span><span class="token builtin">Coordinator</span><span class="token punctuation">.</span>panned<span class="token punctuation">)</span><span class="token punctuation">)</span>
        uiview<span class="token punctuation">.</span><span class="token function">addGestureRecognizer</span><span class="token punctuation">(</span>gesture<span class="token punctuation">)</span>
        <span class="token keyword">return</span> uiview
    <span class="token punctuation">}</span>

    <span class="token keyword">class</span> <span class="token class-name">Coordinator</span><span class="token punctuation">:</span> <span class="token builtin">NSObject</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> tappedCallback<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span>

        <span class="token keyword">init</span><span class="token punctuation">(</span>tappedCallback<span class="token punctuation">:</span> @escaping <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">CGPoint</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">self</span><span class="token punctuation">.</span>tappedCallback <span class="token operator">=</span> tappedCallback
        <span class="token punctuation">}</span>

        <span class="token atrule">@objc</span> <span class="token keyword">func</span> <span class="token function">panned</span><span class="token punctuation">(</span>gesture<span class="token punctuation">:</span><span class="token builtin">UIPanGestureRecognizer</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">if</span> gesture<span class="token punctuation">.</span>state <span class="token operator">==</span> <span class="token punctuation">.</span>began <span class="token operator">||</span> gesture<span class="token punctuation">.</span>state <span class="token operator">==</span> <span class="token punctuation">.</span>changed <span class="token punctuation">{</span>
                <span class="token keyword">let</span> point <span class="token operator">=</span> gesture<span class="token punctuation">.</span><span class="token function">location</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> gesture<span class="token punctuation">.</span>view<span class="token punctuation">)</span>
                <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token function">tappedCallback</span><span class="token punctuation">(</span>point<span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">makeCoordinator</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Background</span><span class="token punctuation">.</span><span class="token builtin">Coordinator</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">Coordinator</span><span class="token punctuation">(</span>tappedCallback<span class="token punctuation">:</span><span class="token keyword">self</span><span class="token punctuation">.</span>tappedCallback<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">updateUIView</span><span class="token punctuation">(</span><span class="token number">_</span> uiView<span class="token punctuation">:</span> <span class="token builtin">UIView</span><span class="token punctuation">,</span> context<span class="token punctuation">:</span> <span class="token builtin">Context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br></div></div><p>このようにかけばドラッグ中に円がちゃんと指についてきて理想的な動作が行える。</p>
<p>ただ、<code>ContentView</code>の書き方の問題でオブジェクト(この場合は円自体)にはタップ判定がないのが困る。</p>
<p>なので、タップ判定を行うバックグラウンドのビューは必ず最後に<code>overlay</code>をするようにしておく。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> location<span class="token punctuation">:</span> <span class="token builtin">CGPoint</span><span class="token operator">?</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Color</span><span class="token punctuation">.</span>clear
            <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span>locationIcon<span class="token punctuation">)</span> <span class="token comment">// 修正</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token builtin">Background</span> <span class="token punctuation">{</span> location <span class="token keyword">in</span>
                <span class="token keyword">self</span><span class="token punctuation">.</span>location <span class="token operator">=</span> location
            <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> locationIcon<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> location <span class="token operator">=</span> <span class="token keyword">self</span><span class="token punctuation">.</span>location <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token function">AnyView</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>blue<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">30</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">position</span><span class="token punctuation">(</span>x<span class="token punctuation">:</span> location<span class="token punctuation">.</span>x<span class="token punctuation">,</span> y<span class="token punctuation">:</span> location<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token function">AnyView</span><span class="token punctuation">(</span><span class="token function">EmptyView</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><p>こうすれば円自体にも<code>TapGesture</code>が利くので理想的な仕様になる。</p>
</template>
