<template><h2 id="ios-における生体認証" tabindex="-1"><a class="header-anchor" href="#ios-における生体認証" aria-hidden="true">#</a> iOS における生体認証</h2>
<p>iOS では FaceID と TouchID の二つの生体認証がパスコード認証とは別に利用できる。</p>
<p>今回はその生体認証をアプリに組み込む方法について学ぶ。まず前提として、パスコードを含めた認証システムを使うには<code>import LocalAuthentication</code>を読み込む必要がある。</p>
<h3 id="認証のプロセス" tabindex="-1"><a class="header-anchor" href="#認証のプロセス" aria-hidden="true">#</a> 認証のプロセス</h3>
<ul>
<li>生体認証が可能かどうかチェックする
<ul>
<li>ここでパスコード認証を許可するかどうかを設定できる</li>
</ul>
</li>
<li>可能であれば生体認証を行なう
<ul>
<li>または生体認証をキャンセルしてパスコード認証を行なう</li>
</ul>
</li>
</ul>
<p>パスコード認証を許可するかどうかのフラグが何故あるかというと、iPhone5 以前のデバイスでは TouchID や FaceID が使用不可であり、そもそもそれ以降のデバイスでも生体認証を登録していないユーザがいるためである。</p>
<p>というわけで、全通りパターン分けをするとこのようになる。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">func</span> <span class="token function">biometricsAuth</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> context <span class="token operator">=</span> <span class="token function">LAContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> reason <span class="token operator">=</span> <span class="token string">"This app uses Touch ID / Face ID to secure your data."</span>
    <span class="token keyword">var</span> authError<span class="token punctuation">:</span> <span class="token builtin">NSError</span><span class="token operator">?</span>

    <span class="token keyword">if</span> context<span class="token punctuation">.</span><span class="token function">canEvaluatePolicy</span><span class="token punctuation">(</span><span class="token punctuation">.</span>deviceOwnerAuthenticationWithBiometrics<span class="token punctuation">,</span> error<span class="token punctuation">:</span> <span class="token operator">&amp;</span>authError<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        context<span class="token punctuation">.</span><span class="token function">evaluatePolicy</span><span class="token punctuation">(</span><span class="token punctuation">.</span>deviceOwnerAuthenticationWithBiometrics<span class="token punctuation">,</span> localizedReason<span class="token punctuation">:</span> reason<span class="token punctuation">)</span> <span class="token punctuation">{</span> success<span class="token punctuation">,</span> error <span class="token keyword">in</span>
            <span class="token keyword">if</span> success <span class="token punctuation">{</span>
                <span class="token comment">// 生体認証が成功した場合</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token comment">// 生体認証が失敗した場合</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        <span class="token comment">// 生体認証ができない場合</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><p>指紋認証のためのボタンは SF symbols で定義されている<code>touchid</code>というやつが使える。</p>
<h2 id="前回のコードとくっつける" tabindex="-1"><a class="header-anchor" href="#前回のコードとくっつける" aria-hidden="true">#</a> 前回のコードとくっつける</h2>
<p>パスコード入力画面に追加して動作チェックをしてみる。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">LocalAuthentication</span>

<span class="token keyword">struct</span> <span class="token builtin">PasscodeView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>

    <span class="token keyword">typealias</span> <span class="token builtin">CompletionHandler</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token builtin">Result</span><span class="token operator">&lt;</span><span class="token builtin">Bool</span><span class="token punctuation">,</span> <span class="token builtin">Error</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span>
    <span class="token keyword">let</span> completionHandler<span class="token punctuation">:</span> <span class="token builtin">CompletionHandler</span>
    <span class="token keyword">let</span> passcode<span class="token punctuation">:</span> <span class="token builtin">Int</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>passcode<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token punctuation">,</span> completionHandler<span class="token punctuation">:</span> @escaping <span class="token builtin">CompletionHandler</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>completionHandler <span class="token operator">=</span> completionHandler
        <span class="token keyword">self</span><span class="token punctuation">.</span>passcode <span class="token operator">=</span> passcode
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">GeometryReader</span> <span class="token punctuation">{</span> geometry <span class="token keyword">in</span>
            <span class="token function">LazyVGrid</span><span class="token punctuation">(</span>columns<span class="token punctuation">:</span> <span class="token function">Array</span><span class="token punctuation">(</span>repeating<span class="token punctuation">:</span> <span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">.</span><span class="token function">flexible</span><span class="token punctuation">(</span>minimum<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> maximum<span class="token punctuation">:</span> <span class="token number">80</span><span class="token punctuation">)</span><span class="token punctuation">,</span> spacing<span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token builtin">count</span><span class="token punctuation">:</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">,</span> spacing<span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">,</span> pinnedViews<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">ForEach</span><span class="token punctuation">(</span><span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token number">9</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> number <span class="token keyword">in</span>
                    <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">addSign</span><span class="token punctuation">(</span>sender<span class="token punctuation">:</span> number<span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>number<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>blue<span class="token punctuation">,</span> lineWidth<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
                <span class="token punctuation">}</span>
                <span class="token punctuation">.</span><span class="token function">buttonStyle</span><span class="token punctuation">(</span><span class="token function">CircleButtonStyle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
                <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">biometricsAuth</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Image</span><span class="token punctuation">(</span>systemName<span class="token punctuation">:</span> <span class="token string">"touchid"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">resizable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">40</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">40</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
                <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">addSign</span><span class="token punctuation">(</span>sender<span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
                    <span class="token punctuation">.</span><span class="token function">buttonStyle</span><span class="token punctuation">(</span><span class="token function">CircleButtonStyle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
                <span class="token function">Button</span><span class="token punctuation">(</span>action<span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> label<span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"Delete"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">60</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token comment">// 認証画面を真ん中に表示</span>
            <span class="token punctuation">.</span><span class="token function">position</span><span class="token punctuation">(</span>x<span class="token punctuation">:</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>width <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">,</span> y<span class="token punctuation">:</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>height <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
        <span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">background</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>white<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">addSign</span><span class="token punctuation">(</span>sender<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> sender <span class="token operator">==</span> passcode <span class="token punctuation">{</span>
            <span class="token function">completionHandler</span><span class="token punctuation">(</span><span class="token punctuation">.</span><span class="token function">success</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token function">completionHandler</span><span class="token punctuation">(</span><span class="token punctuation">.</span><span class="token function">success</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function">biometricsAuth</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> context <span class="token operator">=</span> <span class="token function">LAContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">let</span> reason <span class="token operator">=</span> <span class="token string">"This app uses Touch ID / Face ID to secure your data."</span>
        <span class="token keyword">var</span> authError<span class="token punctuation">:</span> <span class="token builtin">NSError</span><span class="token operator">?</span>

        <span class="token keyword">if</span> context<span class="token punctuation">.</span><span class="token function">canEvaluatePolicy</span><span class="token punctuation">(</span><span class="token punctuation">.</span>deviceOwnerAuthenticationWithBiometrics<span class="token punctuation">,</span> error<span class="token punctuation">:</span> <span class="token operator">&amp;</span>authError<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            context<span class="token punctuation">.</span><span class="token function">evaluatePolicy</span><span class="token punctuation">(</span><span class="token punctuation">.</span>deviceOwnerAuthenticationWithBiometrics<span class="token punctuation">,</span> localizedReason<span class="token punctuation">:</span> reason<span class="token punctuation">)</span> <span class="token punctuation">{</span> success<span class="token punctuation">,</span> error <span class="token keyword">in</span>
                <span class="token keyword">if</span> success <span class="token punctuation">{</span>
                    <span class="token comment">// 生体認証が成功した場合</span>
                    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"SUCCESS"</span><span class="token punctuation">)</span>
                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                    <span class="token comment">// 生体認証が失敗した場合</span>
                    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"FAILURE"</span><span class="token punctuation">)</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token comment">// 生体認証ができない場合</span>
            <span class="token function">print</span><span class="token punctuation">(</span><span class="token string">"FAILURE"</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">struct</span> <span class="token builtin">CircleButtonStyle</span><span class="token punctuation">:</span> <span class="token builtin">ButtonStyle</span> <span class="token punctuation">{</span>
    <span class="token keyword">func</span> <span class="token function">makeBody</span><span class="token punctuation">(</span>configuration<span class="token punctuation">:</span> <span class="token builtin">Configuration</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        configuration<span class="token punctuation">.</span>label
            <span class="token punctuation">.</span><span class="token function">foregroundColor</span><span class="token punctuation">(</span>configuration<span class="token punctuation">.</span>isPressed <span class="token operator">?</span> <span class="token builtin">Color</span><span class="token punctuation">.</span>white <span class="token punctuation">:</span> <span class="token builtin">Color</span><span class="token punctuation">.</span>blue<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">overlay</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>blue<span class="token punctuation">,</span> lineWidth<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">contentShape</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">background</span><span class="token punctuation">(</span><span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">foregroundColor</span><span class="token punctuation">(</span>configuration<span class="token punctuation">.</span>isPressed <span class="token operator">?</span> <span class="token builtin">Color</span><span class="token punctuation">.</span>blue <span class="token punctuation">:</span> <span class="token builtin">Color</span><span class="token punctuation">.</span>clear<span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br><span class="line-number">60</span><br><span class="line-number">61</span><br><span class="line-number">62</span><br><span class="line-number">63</span><br><span class="line-number">64</span><br><span class="line-number">65</span><br><span class="line-number">66</span><br><span class="line-number">67</span><br><span class="line-number">68</span><br><span class="line-number">69</span><br><span class="line-number">70</span><br><span class="line-number">71</span><br><span class="line-number">72</span><br><span class="line-number">73</span><br></div></div></template>
