<template><h2 id="ジェネリクスを学ぼう" tabindex="-1"><a class="header-anchor" href="#ジェネリクスを学ぼう" aria-hidden="true">#</a> ジェネリクスを学ぼう</h2>
<p>Salmonia3 を開発していてよく使うのがオプショナルの数値を文字列に変換する処理である。</p>
<p>要するに、データがないならばないことを意味する<code>-</code>を返し、そうでないならその値をそのまま文字列にして返してほしいのである。ただし、Double 型の場合は小数点が延々と続いては困るので小数第二位で区切ることとする。</p>
<p>これを extension を使うと以下のようにかける。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">Optional</span> <span class="token keyword">where</span> <span class="token builtin">Wrapped</span> <span class="token operator">==</span> <span class="token builtin">Int</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> stringValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token keyword">self</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">"-"</span> <span class="token punctuation">}</span>
        <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Int</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">extension</span> <span class="token builtin">Optional</span> <span class="token keyword">where</span> <span class="token builtin">Wrapped</span> <span class="token operator">==</span> <span class="token builtin">Double</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> stringValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token keyword">self</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">"-"</span> <span class="token punctuation">}</span>
        <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token function">Double</span><span class="token punctuation">(</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Double</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">100</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>本当は「数値であれば～」という処理にしたかったので、</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">Optional</span> <span class="token keyword">where</span> <span class="token builtin">Wrapped</span> <span class="token operator">==</span> <span class="token builtin">Numeric</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> stringValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token keyword">self</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">"-"</span> <span class="token punctuation">}</span>
        <span class="token keyword">switch</span> <span class="token keyword">self</span> <span class="token punctuation">{</span>
        <span class="token keyword">case</span> <span class="token keyword">is</span> <span class="token builtin">Int</span><span class="token punctuation">:</span>
            <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Int</span><span class="token punctuation">)</span>
        <span class="token keyword">case</span> <span class="token keyword">is</span> <span class="token builtin">Double</span><span class="token punctuation">:</span>
            <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token function">Double</span><span class="token punctuation">(</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Double</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">100</span><span class="token punctuation">)</span>
        <span class="token keyword">default</span><span class="token punctuation">:</span>
            <span class="token keyword">return</span> <span class="token string">"-"</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>こういうふうにかければいいのだが、書けなかった。なんでなのん。</p>
<h2 id="ジェネリクスを書いてみる" tabindex="-1"><a class="header-anchor" href="#ジェネリクスを書いてみる" aria-hidden="true">#</a> ジェネリクスを書いてみる</h2>
<p>ここまでできたら、次は SwiftUI で文字列型とオプショナル型を受け付ける関数を書いてみる。</p>
<p>作りたいのはこういうのである。要するにオプショナル型で値を受け取って文字列に直して「パラメータ名 -&gt; 値」というビューである。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">HStack</span> <span class="token punctuation">{</span>
            <span class="token function">Text</span><span class="token punctuation">(</span>title<span class="token punctuation">)</span>
            <span class="token function">Spacer</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token function">Text</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">foregroundColor</span><span class="token punctuation">(</span><span class="token punctuation">.</span>secondary<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><p>じゃあ当然これのイニシャライザが必要になる。やりたいことは以下のようなコードである。だが、これはうまくいかない。なぜなら value は<code>Optional&lt;Any&gt;</code>であり<code>Optional&lt;Int&gt;</code>や<code>Optional&lt;Double&gt;</code>ではないからだ。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">var</span> title<span class="token punctuation">:</span> <span class="token builtin">String</span>
<span class="token keyword">var</span> value<span class="token punctuation">:</span> <span class="token builtin">String</span>

<span class="token keyword">init</span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Any</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>ではどうすればいいかを考えてみよう。</p>
<h3 id="optional-int" tabindex="-1"><a class="header-anchor" href="#optional-int" aria-hidden="true">#</a> Optional&lt;Int&gt;</h3>
<p>こう書けば<code>Int?</code>に対しては正しく処理ができる。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">init</span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>また、これはジェネリクスを使って以下のようにも書ける。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Any</span><span class="token operator">></span><span class="token operator">></span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> T<span class="token punctuation">)</span> <span class="token keyword">where</span> <span class="token builtin">Wrapped</span> <span class="token operator">==</span> <span class="token builtin">Int</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>ジェネリクスは<code>Optional&lt;Any&gt;</code>を許可しているが、その次の<code>Wrapped == Int</code>によってアンラップしたら Int 型でなければいけないという制約をつけているのである。</p>
<p>この二つによって、実質的に引数は<code>Int?</code>しか許容されなくなる。</p>
<h3 id="何故か書けない書き方" tabindex="-1"><a class="header-anchor" href="#何故か書けない書き方" aria-hidden="true">#</a> 何故か書けない書き方</h3>
<p>いけそうなのに何故か書けないジェネリクスたちを供養として載せておきます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span>T<span class="token operator">></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>

<span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">></span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> T<span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>

<span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token operator">></span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> T<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p>Int が書ければ Double は同じように書ける。が、必要なのはそこではない。Double も Int もとってこれるようにしたいのである。</p>
<h2 id="こういうのも書けない" tabindex="-1"><a class="header-anchor" href="#こういうのも書けない" aria-hidden="true">#</a> こういうのも書けない</h2>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Any</span><span class="token operator">></span><span class="token operator">></span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> T<span class="token punctuation">)</span> <span class="token keyword">where</span> <span class="token builtin">Wrapped</span> <span class="token operator">==</span> <span class="token builtin">Int</span><span class="token punctuation">,</span> <span class="token builtin">Double</span> <span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>なのでこれらを組み合わせた以下のようなコードを書く。</p>
<p>これしかないのかなあという気持ち。結局ジェネリクス使ってないし何だこれ。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">init</span><span class="token punctuation">(</span>title<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> value<span class="token punctuation">:</span> <span class="token builtin">Optional</span><span class="token operator">&lt;</span><span class="token builtin">Any</span><span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token keyword">self</span><span class="token punctuation">.</span>title <span class="token operator">=</span> title
    <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value<span class="token punctuation">.</span>stringValue
<span class="token punctuation">}</span>

<span class="token keyword">extension</span> <span class="token builtin">Optional</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> stringValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">switch</span> <span class="token keyword">self</span> <span class="token punctuation">{</span>
        <span class="token keyword">case</span> <span class="token keyword">is</span> <span class="token builtin">Int</span><span class="token punctuation">:</span>
            <span class="token keyword">guard</span> <span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token keyword">self</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">"-"</span> <span class="token punctuation">}</span>
            <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Int</span><span class="token punctuation">)</span>
        <span class="token keyword">case</span> <span class="token keyword">is</span> <span class="token builtin">Double</span><span class="token punctuation">:</span>
            <span class="token keyword">guard</span> <span class="token keyword">let</span> value <span class="token operator">=</span> <span class="token keyword">self</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">"-"</span> <span class="token punctuation">}</span>
            <span class="token keyword">return</span> <span class="token function">String</span><span class="token punctuation">(</span><span class="token function">Double</span><span class="token punctuation">(</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token keyword">self</span> <span class="token keyword">as</span><span class="token operator">!</span> <span class="token builtin">Double</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">100</span><span class="token punctuation">)</span>
        <span class="token keyword">default</span><span class="token punctuation">:</span>
            <span class="token keyword">return</span> <span class="token string">"-"</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div></template>
