<template><h2 id="oauth-認証のための手順" tabindex="-1"><a class="header-anchor" href="#oauth-認証のための手順" aria-hidden="true">#</a> OAuth 認証のための手順</h2>
<h3 id="verifier-と-challenge" tabindex="-1"><a class="header-anchor" href="#verifier-と-challenge" aria-hidden="true">#</a> Verifier と Challenge</h3>
<p>S256 という認証システムを使う場合、Verifier と Challenge の関係は以下のようになる。</p>
<p><code>Challenge = BASE64URL-ENCODE(SHA256(ASCII(Verifier)))</code></p>
<p>ここで注意しなければいけないのは ASCII から SHA256 に変換する際に一度文字列を経由するとバグってしまうということだ。ここで詰まると無限に時間を消費するので気をつけてほしい。単なる SHA256 ハッシュと S256 アルゴリズムで使うハッシュ生成は全く異なるのだ。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">CryptoKit</span>
<span class="token keyword">import</span> <span class="token builtin">Fundation</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>暗号化ライブラリを使うので CryptoKit を、Data 型を扱うので Fundation を import しておこう。</p>
<h3 id="ランダム文字列-verifier" tabindex="-1"><a class="header-anchor" href="#ランダム文字列-verifier" aria-hidden="true">#</a> ランダム文字列: Verifier</h3>
<p>OAuth で認証するためには Verifier と Challenge と呼ばれる二つのパラメータが必要になってくる。Verifier はある程度長い（64 や 128 が推奨されているようだ）ランダム文字列であり、Challenge は Verifier の SHA256 のハッシュとなっている。</p>
<p>SHA256 は Swift の場合 CryptoKit と呼ばれる iOS13 から解禁された標準ライブラリが使える。iOS13 未満の場合は CryptoSwift や Objective-C の機能である CommonCrypto を使うことになるだろう。今回は CryptoKit を用いた場合のコーディングについて解説する。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
    <span class="token keyword">static</span> <span class="token keyword">func</span> <span class="token function">randomString</span><span class="token punctuation">(</span><span class="token number">_</span> length<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">128</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> base<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token builtin">String</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~"</span><span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token function">String</span><span class="token punctuation">(</span>$<span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token keyword">var</span> random<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token string">""</span>
        <span class="token keyword">for</span> <span class="token number">_</span> <span class="token keyword">in</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            random <span class="token operator">+</span><span class="token operator">=</span> base<span class="token punctuation">.</span><span class="token function">randomElement</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">!</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> random
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>上のコードはランダム文字列を生成するため Extension である。Swift4.2 以前は arc4random といった C 言語から引っ張ってきた関数を使う必要があったのだが、現在では標準乱数生成メソッドが使えるのでそれを利用する。</p>
<p>ポイントとしては予め使われる可能性のある文字を文字列にしておき、そこから一文字区切りの配列をつくるという点である。そしてその配列からランダムに 128 回値を選び、それらを結合するというわけである。単に map を使うと String 型ではなく Character 型の配列になってしまうので型変換をする。</p>
<p>文字列から配列をつくるにあたって、<a href="https://qiita.com/rondine-jumpei/items/a298bf4e0612166e5dd5" target="_blank" rel="noopener noreferrer">こちらのコード<OutboundLink/></a>が大変参考になりました。</p>
<p>128 回ループして結合するというコードはとりあえず For 文で書いたのだがとてもダサいのでなんとかしたい所存である。</p>
<p>気になる点としては暗号論的に安全な乱数になっているかというところであるが、まあ気にしなくても多分大丈夫だろう、多分。もしも<code>randomElement()</code>に何らかの偏りがある場合、Verifier を推察される可能性があり、危険である。</p>
<h2 id="sha256-challenge" tabindex="-1"><a class="header-anchor" href="#sha256-challenge" aria-hidden="true">#</a> SHA256: Challenge</h2>
<p>次にこのランダム文字列を SHA256 に変換する。CryptoKit の SHA256 でハッシュを求めるアルゴリズムは引数が Data 型であり String 型ではないので、文字列を Data 型に変換する必要がある。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// OK</span>
<span class="token keyword">extension</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> sha256<span class="token punctuation">:</span> <span class="token builtin">SHA256</span><span class="token punctuation">.</span><span class="token builtin">Digest</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token builtin">SHA256</span><span class="token punctuation">.</span><span class="token function">hash</span><span class="token punctuation">(</span>data<span class="token punctuation">:</span> <span class="token function">Data</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">.</span>utf8<span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>というわけで、String 型の Extension を拡張してそれ自身の SHA256 ハッシュを返せるようにした。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// NG</span>
<span class="token keyword">extension</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> sha256<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token builtin">SHA256</span><span class="token punctuation">.</span><span class="token function">hash</span><span class="token punctuation">(</span>data<span class="token punctuation">:</span> <span class="token function">Data</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">.</span>utf8<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>compactMap<span class="token punctuation">{</span><span class="token function">String</span><span class="token punctuation">(</span>format<span class="token punctuation">:</span> <span class="token string">"%02x"</span><span class="token punctuation">,</span> $<span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">.</span><span class="token function">joined</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>ちなみに、上のようなコードを書くと文字列を経由してしまい失敗する。こちらは単に SHA256 のハッシュが欲しい場合に使うと良い。</p>
<p>SHA256 ハッシュ作成に関しては<a href="https://rono23.com/posts/pkec-code-challenge/" target="_blank" rel="noopener noreferrer">こちらのページ<OutboundLink/></a>が大変参考になりました。</p>
<h2 id="base64encode-challenge" tabindex="-1"><a class="header-anchor" href="#base64encode-challenge" aria-hidden="true">#</a> Base64Encode: Challenge</h2>
<p>実は Challenge は単なる SHA256 ハッシュではなく、そのハッシュを Base64 エンコードしたものとなっている。なぜ二回ハッシュを計算するのかわからないが（しかも Base64 は安全なハッシュとは言えない）、仕様書でそうなっているのでそうするしかない。</p>
<p>SHA256 のハッシュから直接 Base64 を返したいので標準ライブラリを用いて以下のように実装した。PKCE では Base64 の値のうち「=」、「+」、「/」の三つについては正しくエスケープしないといけない。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">SHA256</span><span class="token punctuation">.</span><span class="token builtin">Digest</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> base64EncodedString<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">Data</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">base64EncodedString</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">replacingOccurrences</span><span class="token punctuation">(</span>of<span class="token punctuation">:</span> <span class="token string">"="</span><span class="token punctuation">,</span> with<span class="token punctuation">:</span> <span class="token string">""</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">replacingOccurrences</span><span class="token punctuation">(</span>of<span class="token punctuation">:</span> <span class="token string">"+"</span><span class="token punctuation">,</span> with<span class="token punctuation">:</span> <span class="token string">"-"</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">replacingOccurrences</span><span class="token punctuation">(</span>of<span class="token punctuation">:</span> <span class="token string">"/"</span><span class="token punctuation">,</span> with<span class="token punctuation">:</span> <span class="token string">"_"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p>なので非常に冗長になるが、<code>base64EncodedString()</code>を拡張して PKCE 用の Base64 文字列を返すようにした。</p>
<p>この状態で<code>E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM</code>を Verifier として設定し、Challenge を計算すると正しく<code>E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM</code>を得ることができた。</p>
</template>
