<template><h2 id="property-wrapper-とは" tabindex="-1"><a class="header-anchor" href="#property-wrapper-とは" aria-hidden="true">#</a> Property Wrapper とは</h2>
<p>そもそも Property Wrapper がいったいなんなのかよくわかっていなかったので調べてみました。</p>
<p><a href="https://qiita.com/favolabo/items/67308dbcf88f3bc1d65f" target="_blank" rel="noopener noreferrer">こちらの記事<OutboundLink/></a>が参考になったので載せておきます。</p>
<p>これによると「変数をラッピングして get や set を制御するための仕組み」とあります。しかし、Swift では普通に get や set を実行できるので、わざわざ Property Wrapper を使う必要がないような気もします。</p>
<p>一体、これを使うとどのように便利になるのかを調べていきましょう。</p>
<h3 id="サンプルコード" tabindex="-1"><a class="header-anchor" href="#サンプルコード" aria-hidden="true">#</a> サンプルコード</h3>
<p>例えば、以下のような構造体を考えます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>

<span class="token keyword">struct</span> <span class="token builtin">HelloWorld</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> text<span class="token punctuation">:</span> <span class="token builtin">String</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        text <span class="token operator">=</span> <span class="token string">""</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> wrappedValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">get</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> text <span class="token punctuation">}</span>
        <span class="token keyword">set</span> <span class="token punctuation">{</span> text <span class="token operator">=</span> <span class="token string">"Hello, <span class="token interpolation"><span class="token delimiter variable">\(</span>newValue<span class="token delimiter variable">)</span></span>"</span> <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p>この構造体は外部から参照できない内部プロパティ<code>text</code>を保持しており、その値は最初は空文字です。そして、<code>text</code>自体にはアクセスできないものの計算プロパティである<code>wrappedValue</code>を介して間接的に<code>text</code>の中身を参照できます。</p>
<p>単に参照（get）した場合は<code>text</code>の中身は空文字のままなので空文字が返ってきますが、<code>wrappedValue</code>に一度でも値を代入した場合は<code>text</code>の値が書き換えられます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">var</span> world <span class="token operator">=</span> <span class="token function">HelloWorld</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
world<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token string">"world!"</span>
<span class="token function">print</span><span class="token punctuation">(</span>world<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span> <span class="token comment">// -> Hello, world!</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>よって、上のコードを実行した場合には<code>Hello, world!</code>が出力されるというわけです。</p>
<p>これだけでも別に不満はないのですが、いちいち構造体を宣言してインスタンスをつくったり、値を代入するコードを書いたりというめんどくささがあります。</p>
<p>Property Wrapper はこの煩わしさを解消するための仕組みなのです。</p>
<h3 id="property-wrapper-を適用する" tabindex="-1"><a class="header-anchor" href="#property-wrapper-を適用する" aria-hidden="true">#</a> Property Wrapper を適用する</h3>
<p>Property Wrapper は Class、Struct、Enum に対して使えるとのことです。</p>
<p>使い方も簡単で宣言の前に<code>@propertyWrapper</code>と書くだけです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>

@propertyWrapper
<span class="token keyword">struct</span> <span class="token builtin">HelloWorld</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> text<span class="token punctuation">:</span> <span class="token builtin">String</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        text <span class="token operator">=</span> <span class="token string">""</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">var</span> wrappedValue<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">get</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> text <span class="token punctuation">}</span>
        <span class="token keyword">set</span> <span class="token punctuation">{</span> text <span class="token operator">=</span> <span class="token string">"Hello, <span class="token interpolation"><span class="token delimiter variable">\(</span>newValue<span class="token delimiter variable">)</span></span>"</span> <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><p>Property Wrapper は必ず<code>wrappedValue</code>というプロパティをもたなければいけません。</p>
<p>また、<code>wrappedValue</code>とは別に<code>projectedValue</code>というプロパティをもたせることもできます。</p>
<p>Property Wrapper を使えば先程のコードは以下のように書き直せます。こっちのほうがスッキリしていて書きやすいですね。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>@<span class="token builtin">HelloWorld</span> <span class="token keyword">var</span> message<span class="token punctuation">:</span> <span class="token builtin">String</span>
message <span class="token operator">=</span> <span class="token string">"world!"</span>
<span class="token function">print</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span> <span class="token comment">// -> Hello, world!</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="appstorage-のようなクラスを作成する" tabindex="-1"><a class="header-anchor" href="#appstorage-のようなクラスを作成する" aria-hidden="true">#</a> AppStorage のようなクラスを作成する</h2>
<p><code>AppStorage</code>は UserDefaults を Property Wrapper 拡張したようなもので、簡単に UserDefaults の値を使えるという点では便利でした。</p>
<p>ただ、<code>AppStorage</code>は常に文字列型のリテラルを代入しなければならず、値を再利用したいときなどには Typo してしまうなどの問題点がありました。</p>
<p>そこで、これを解決するために UserDefaults + AppStorage のいいとこ取りをしたような UserStorage の Property Wrapper を作成しました。</p>
<p>なお、コーディングに関しては AppStorage を iOS13 に移植するコードである<a href="https://github.com/xavierLowmiller/AppStorage" target="_blank" rel="noopener noreferrer">AppStorage<OutboundLink/></a>を大いに参考にさせていただきました。</p>
<h2 id="文字列型-enum-全てを許容する" tabindex="-1"><a class="header-anchor" href="#文字列型-enum-全てを許容する" aria-hidden="true">#</a> 文字列型 Enum 全てを許容する</h2>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// UserStorage.swift</span>
<span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Foundation</span>

@usableFromInline
<span class="token keyword">final</span> <span class="token keyword">class</span> <span class="token class-name">Storage</span><span class="token operator">&lt;</span><span class="token builtin">Value</span><span class="token operator">></span><span class="token punctuation">:</span> <span class="token builtin">NSObject</span><span class="token punctuation">,</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> value<span class="token punctuation">:</span> <span class="token builtin">Value</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> defaultValue<span class="token punctuation">:</span> <span class="token builtin">Value</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> keyPath<span class="token punctuation">:</span> <span class="token builtin">String</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> transform<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token builtin">Any</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Value</span><span class="token operator">?</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> <span class="token builtin">Value</span><span class="token punctuation">,</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span><span class="token punctuation">,</span> key<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> transform<span class="token punctuation">:</span> @escaping <span class="token punctuation">(</span><span class="token builtin">Any</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Value</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> value
        <span class="token keyword">self</span><span class="token punctuation">.</span>defaultValue <span class="token operator">=</span> value
        <span class="token keyword">self</span><span class="token punctuation">.</span>store <span class="token operator">=</span> store
        <span class="token keyword">self</span><span class="token punctuation">.</span>keyPath <span class="token operator">=</span> key
        <span class="token keyword">self</span><span class="token punctuation">.</span>transform <span class="token operator">=</span> transform
        <span class="token keyword">super</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

        store<span class="token punctuation">.</span><span class="token function">addObserver</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">,</span> forKeyPath<span class="token punctuation">:</span> key<span class="token punctuation">,</span> options<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">.</span><span class="token keyword">new</span><span class="token punctuation">]</span><span class="token punctuation">,</span> context<span class="token punctuation">:</span> <span class="token constant">nil</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">deinit</span> <span class="token punctuation">{</span>
        store<span class="token punctuation">.</span><span class="token function">removeObserver</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">,</span> forKeyPath<span class="token punctuation">:</span> keyPath<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">override</span> <span class="token keyword">func</span> <span class="token function">observeValue</span><span class="token punctuation">(</span>forKeyPath keyPath<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token operator">?</span><span class="token punctuation">,</span>
                               of object<span class="token punctuation">:</span> <span class="token builtin">Any</span><span class="token operator">?</span><span class="token punctuation">,</span>
                               change<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token builtin">NSKeyValueChangeKey</span> <span class="token punctuation">:</span> <span class="token builtin">Any</span><span class="token punctuation">]</span><span class="token operator">?</span><span class="token punctuation">,</span>
                               context<span class="token punctuation">:</span> <span class="token builtin">UnsafeMutableRawPointer</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

        value <span class="token operator">=</span> change<span class="token operator">?</span><span class="token punctuation">[</span><span class="token punctuation">.</span>newKey<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">flatMap</span><span class="token punctuation">(</span>transform<span class="token punctuation">)</span> <span class="token operator">?</span><span class="token operator">?</span> defaultValue
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

@frozen @propertyWrapper <span class="token keyword">public</span> <span class="token keyword">struct</span> <span class="token builtin">UserStorage</span><span class="token operator">&lt;</span><span class="token builtin">Value</span><span class="token operator">></span><span class="token punctuation">:</span> <span class="token builtin">DynamicProperty</span> <span class="token punctuation">{</span>
    @<span class="token builtin">ObservedObject</span> <span class="token keyword">private</span> <span class="token keyword">var</span> value<span class="token punctuation">:</span> <span class="token builtin">Storage</span><span class="token operator">&lt;</span><span class="token builtin">Value</span><span class="token operator">></span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> saveValue<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token builtin">Value</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span>

    <span class="token keyword">private</span> <span class="token keyword">init</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> <span class="token builtin">Value</span><span class="token punctuation">,</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span><span class="token punctuation">,</span> key<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> transform<span class="token punctuation">:</span> @escaping <span class="token punctuation">(</span><span class="token builtin">Any</span><span class="token operator">?</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Value</span><span class="token operator">?</span><span class="token punctuation">,</span> saveValue<span class="token punctuation">:</span> @escaping <span class="token punctuation">(</span><span class="token builtin">Value</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Void</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

        <span class="token keyword">self</span><span class="token punctuation">.</span>value <span class="token operator">=</span> <span class="token function">Storage</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> value<span class="token punctuation">,</span> store<span class="token punctuation">:</span> store<span class="token punctuation">,</span> key<span class="token punctuation">:</span> key<span class="token punctuation">,</span> transform<span class="token punctuation">:</span> transform<span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>saveValue <span class="token operator">=</span> saveValue
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">var</span> wrappedValue<span class="token punctuation">:</span> <span class="token builtin">Value</span> <span class="token punctuation">{</span>
        <span class="token keyword">get</span> <span class="token punctuation">{</span> value<span class="token punctuation">.</span>value <span class="token punctuation">}</span>
        <span class="token keyword">nonmutating</span> <span class="token keyword">set</span> <span class="token punctuation">{</span>
            <span class="token function">saveValue</span><span class="token punctuation">(</span>newValue<span class="token punctuation">)</span>
            value<span class="token punctuation">.</span>value <span class="token operator">=</span> newValue
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">var</span> projectedValue<span class="token punctuation">:</span> <span class="token builtin">Binding</span><span class="token operator">&lt;</span><span class="token builtin">Value</span><span class="token operator">></span> <span class="token punctuation">{</span>
        <span class="token function">Binding</span><span class="token punctuation">(</span>
            <span class="token keyword">get</span><span class="token punctuation">:</span> <span class="token punctuation">{</span> wrappedValue <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token keyword">set</span><span class="token punctuation">:</span> <span class="token punctuation">{</span> wrappedValue <span class="token operator">=</span> $<span class="token number">0</span> <span class="token punctuation">}</span>
        <span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">extension</span> <span class="token builtin">UserStorage</span> <span class="token keyword">where</span> <span class="token builtin">Value</span> <span class="token operator">==</span> <span class="token builtin">Bool</span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">RawRepresentable</span><span class="token operator">></span><span class="token punctuation">(</span>wrappedValue<span class="token punctuation">:</span> <span class="token builtin">Value</span><span class="token punctuation">,</span> <span class="token number">_</span> key<span class="token punctuation">:</span> T<span class="token punctuation">,</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token constant">nil</span><span class="token punctuation">)</span> <span class="token keyword">where</span> T<span class="token punctuation">.</span><span class="token builtin">RawValue</span> <span class="token operator">==</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> store <span class="token operator">=</span> <span class="token punctuation">(</span>store <span class="token operator">?</span><span class="token operator">?</span> <span class="token punctuation">.</span>standard<span class="token punctuation">)</span>
        <span class="token keyword">let</span> initialValue <span class="token operator">=</span> store<span class="token punctuation">.</span><span class="token function">value</span><span class="token punctuation">(</span>forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token operator">?</span><span class="token operator">?</span> wrappedValue
        <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> initialValue<span class="token punctuation">,</span> store<span class="token punctuation">:</span> store<span class="token punctuation">,</span> key<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">,</span> transform<span class="token punctuation">:</span> <span class="token punctuation">{</span> $<span class="token number">0</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> saveValue<span class="token punctuation">:</span> <span class="token punctuation">{</span> newValue <span class="token keyword">in</span>
            store<span class="token punctuation">.</span><span class="token function">setValue</span><span class="token punctuation">(</span>newValue<span class="token punctuation">,</span> forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br><span class="line-number">60</span><br><span class="line-number">61</span><br><span class="line-number">62</span><br><span class="line-number">63</span><br><span class="line-number">64</span><br><span class="line-number">65</span><br><span class="line-number">66</span><br><span class="line-number">67</span><br><span class="line-number">68</span><br><span class="line-number">69</span><br><span class="line-number">70</span><br><span class="line-number">71</span><br></div></div><p>上半分は難しいのでおいておくとして、大事なのは最後の Extension です。これは UserDefaults に保存する値が Bool の場合のものですが、Int や Double も保存したければこの Extension をまるまるコピペして<code>Value == XXX</code>の<code>XXX</code>の部分を置き換えれば動作します。</p>
<p>例えば、整数を保存したい場合は次のような Extension を追記してください。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">UserStorage</span> <span class="token keyword">where</span> <span class="token builtin">Value</span> <span class="token operator">==</span> <span class="token builtin">Int</span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">init</span><span class="token operator">&lt;</span>T<span class="token punctuation">:</span> <span class="token builtin">RawRepresentable</span><span class="token operator">></span><span class="token punctuation">(</span>wrappedValue<span class="token punctuation">:</span> <span class="token builtin">Value</span><span class="token punctuation">,</span> <span class="token number">_</span> key<span class="token punctuation">:</span> T<span class="token punctuation">,</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token constant">nil</span><span class="token punctuation">)</span> <span class="token keyword">where</span> T<span class="token punctuation">.</span><span class="token builtin">RawValue</span> <span class="token operator">==</span> <span class="token builtin">String</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> store <span class="token operator">=</span> <span class="token punctuation">(</span>store <span class="token operator">?</span><span class="token operator">?</span> <span class="token punctuation">.</span>standard<span class="token punctuation">)</span>
        <span class="token keyword">let</span> initialValue <span class="token operator">=</span> store<span class="token punctuation">.</span><span class="token function">value</span><span class="token punctuation">(</span>forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token operator">?</span><span class="token operator">?</span> wrappedValue
        <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> initialValue<span class="token punctuation">,</span> store<span class="token punctuation">:</span> store<span class="token punctuation">,</span> key<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">,</span> transform<span class="token punctuation">:</span> <span class="token punctuation">{</span> $<span class="token number">0</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> saveValue<span class="token punctuation">:</span> <span class="token punctuation">{</span> newValue <span class="token keyword">in</span>
            store<span class="token punctuation">.</span><span class="token function">setValue</span><span class="token punctuation">(</span>newValue<span class="token punctuation">,</span> forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>ただ、保存先が UserDefaults である以上、UserDefaults に保存できないデータはアプリがクラッシュするので使うことができません。</p>
<p>UserDefaults に保存できるのは、Bool, Int, Double, String, Data, Date, Array, Dictionary に限られます。ただ、本系の AppStorage では Array は保存することができないので、こっちのコードのほうが少し便利かもしれません。</p>
<h3 id="使い方" tabindex="-1"><a class="header-anchor" href="#使い方" aria-hidden="true">#</a> 使い方</h3>
<p>初回起動かどうか、起動回数が何回かを UserDefaults に保存したい場合を考えます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token builtin">UserDefaultsKey</span><span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> <span class="token builtin">CaseIterable</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> isFirstLaunch
    <span class="token keyword">case</span> launchCount
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>その時、上のような Enum を定義します。<code>CaseIterable</code>に準拠する必要はありませんが、<code>String</code>には準拠する必要があります。そうでないと<code>rawValue</code>が使えず、UserDefaults のキー指定ができないためです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>@<span class="token function">UserStorage</span><span class="token punctuation">(</span><span class="token builtin">UserDefaultsKey</span><span class="token punctuation">.</span>isFirstLaunch<span class="token punctuation">)</span> <span class="token keyword">var</span> isFirstLaunch<span class="token punctuation">:</span> <span class="token builtin">Bool</span> <span class="token operator">=</span> <span class="token boolean">false</span>
@<span class="token function">UserStorage</span><span class="token punctuation">(</span><span class="token builtin">UserDefaultsKey</span><span class="token punctuation">.</span>isSecurityLock<span class="token punctuation">)</span> <span class="token keyword">var</span> isSecurityLock<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>あとはこのように宣言すれば<code>AppStorage</code>と全く同じように使えます。</p>
<h2 id="一つの-enum-しか使わない場合" tabindex="-1"><a class="header-anchor" href="#一つの-enum-しか使わない場合" aria-hidden="true">#</a> 一つの Enum しか使わない場合</h2>
<p>さっきのコードは String を継承した Enum であれば何でも指定できましたが、実際にそのような場面は少ないかと思います。</p>
<p>何故なら UserDefaults はキーが文字列しかないため、キーが被るという可能性が非常に高いからです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token builtin">UserKey</span><span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> <span class="token builtin">CaseIterable</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> contractId
<span class="token punctuation">}</span>

<span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token builtin">CompanyKey</span><span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> <span class="token builtin">CaseIterable</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> contractId
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>例えばこのように UserKey と CompanyKey のようなものを作成し、UserDefaults に保存しようとすると<code>contractId</code>の値が重複してしまいデータが上書きされてしまいます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token builtin">UserKey</span><span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> <span class="token builtin">CaseIterable</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> contractId <span class="token operator">=</span> <span class="token string">"userContractId"</span>
<span class="token punctuation">}</span>

<span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token builtin">CompanyKey</span><span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">,</span> <span class="token builtin">CaseIterable</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> contractId <span class="token operator">=</span> <span class="token string">"companyContractId"</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>というように変数名そのままではないリテラルを与えればこの問題は回避できますが、結局これはどことどこで名前衝突が起こっているかがわかっていないとこういう対策はできません。</p>
<p>第一、こういう対策は抜本的ではないです。</p>
<p>こういう名前衝突が起こるのはそもそものプロジェクトの仕様の問題であり、UserDefaults ではなくデータベースや Core Data を使用するように変更すべきでしょう。</p>
<p>なので、複数の Enum がこの UserStorage を使うことはないだろうと考えます。</p>
<p>そうであれば先程のコードは少し短くなります。さっきまではジェネリクスで判定をしていましたがそれが不要になるわけです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token builtin">UserStorage</span> <span class="token keyword">where</span> <span class="token builtin">Value</span> <span class="token operator">==</span> <span class="token builtin">Bool</span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">init</span><span class="token punctuation">(</span>wrappedValue<span class="token punctuation">:</span> <span class="token builtin">Value</span><span class="token punctuation">,</span> <span class="token number">_</span> key<span class="token punctuation">:</span> <span class="token builtin">UserDefaultsKey</span><span class="token punctuation">,</span> store<span class="token punctuation">:</span> <span class="token builtin">UserDefaults</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token constant">nil</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> store <span class="token operator">=</span> <span class="token punctuation">(</span>store <span class="token operator">?</span><span class="token operator">?</span> <span class="token punctuation">.</span>standard<span class="token punctuation">)</span>
        <span class="token keyword">let</span> initialValue <span class="token operator">=</span> store<span class="token punctuation">.</span><span class="token function">value</span><span class="token punctuation">(</span>forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token operator">?</span><span class="token operator">?</span> wrappedValue
        <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> initialValue<span class="token punctuation">,</span> store<span class="token punctuation">:</span> store<span class="token punctuation">,</span> key<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">,</span> transform<span class="token punctuation">:</span> <span class="token punctuation">{</span> $<span class="token number">0</span> <span class="token keyword">as</span><span class="token operator">?</span> <span class="token builtin">Value</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> saveValue<span class="token punctuation">:</span> <span class="token punctuation">{</span> newValue <span class="token keyword">in</span>
            store<span class="token punctuation">.</span><span class="token function">setValue</span><span class="token punctuation">(</span>newValue<span class="token punctuation">,</span> forKey<span class="token punctuation">:</span> key<span class="token punctuation">.</span>rawValue<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div></template>
