<template><h2 id="スクリーンセーバーとは" tabindex="-1"><a class="header-anchor" href="#スクリーンセーバーとは" aria-hidden="true">#</a> スクリーンセーバーとは</h2>
<p>スクリーンセーバーとは長時間同じ画面を表示し続けると画面が焼き付きを起こしてしまうため、それを防ぐために一定時間操作がないと別のアニメーションを表示するような仕組みのことを指す。</p>
<p>最近のモニタはそもそも焼き付きを起こしにくい上、一定時間の無操作で勝手に画面がオフになるためスクリーンセーバーが必要とされる場面は少ない。</p>
<p>また、モバイル向けアプリであれば長時間ずっと画面がついているとそれこそバッテリーの無駄なのでシステム的にしばらく操作しないでいると勝手に画面がオフになる。したがって、モバイルアプリでスクリーンセーバーが必要になる場面は基本的には考えられない。</p>
<h3 id="情報を調べてみる" tabindex="-1"><a class="header-anchor" href="#情報を調べてみる" aria-hidden="true">#</a> 情報を調べてみる</h3>
<p>そもそも必要とされていないだけあって、情報が殆ど見つからなかった。</p>
<p><a href="https://developer.apple.com/documentation/screensaver/screensaverview" target="_blank" rel="noopener noreferrer">ScreenSaverView<OutboundLink/></a>というクラス自体は存在するようなのだが、macOS 向けであり iOS 向けには実装されていない。</p>
<p>そもそも、スクリーンセーバーを実装するためには「N 秒間操作されていない」という情報を持っていなければいけない。スクリーンセーバーの実装ためだけにわざわざ何もしなくていい時間にそういったコードが裏で動いていなければいけないのだ。</p>
<p>うーん、やはりスクリーンセーバーを実装するメリットはないように感じますね。</p>
<p>が、電源挿しっぱなしでなにかの情報を表示し続けるようなアプリであればスクリーンセーバー的な機能が欲しくなるのもまた理解できます。</p>
<p>ここは、なんとかして実装することを考えてみましょう。</p>
<h2 id="実装してみよう" tabindex="-1"><a class="header-anchor" href="#実装してみよう" aria-hidden="true">#</a> 実装してみよう</h2>
<p>調べてみたところ愚直に Timer を使う方法と、Combine を使ってちょっとそれっぽく書く方法があるようです。</p>
<p>今回はどちらのコードも調べ、等価なプログラムを書いてみることにしました。</p>
<h3 id="timer-を利用する" tabindex="-1"><a class="header-anchor" href="#timer-を利用する" aria-hidden="true">#</a> Timer を利用する</h3>
<p>まず簡単に実装できそうな Timer を利用してみます。Timer の使い方自体はよくわかっていないのですが、<a href="https://www.hackingwithswift.com/quick-start/swiftui/how-to-use-a-timer-with-swiftui" target="_blank" rel="noopener noreferrer">HACKING WITH SWIFT<OutboundLink/></a>のページのチュートリアルがわかりやすいと思います。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> timeRemaining <span class="token operator">=</span> <span class="token number">10</span>
    <span class="token keyword">let</span> timer <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>timeRemaining<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">onReceive</span><span class="token punctuation">(</span>timer<span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token number">_</span> <span class="token keyword">in</span>
                <span class="token keyword">if</span> timeRemaining <span class="token operator">></span> <span class="token number">0</span> <span class="token punctuation">{</span>
                    timeRemaining <span class="token operator">-</span><span class="token operator">=</span> <span class="token number">1</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>Timer は 1 秒おきに publish で更新をかけ、<code>onReceive</code>で Timer の値が変化したときに何らかの操作を行なうわけです。</p>
<p>このチュートリアルの場合ではテキストの値を変更しているので、テキストの中身である<code>timeRemainig</code>が<code>@State</code>になっているわけですね。</p>
<p>ちなみに publish されている値は<code>2021-04-25 23:55:24 +0000</code>のような値になります。日付を表示したいのであればこのデータをそのまま利用するのもありかもしれません。</p>
<h3 id="playground-向けコード" tabindex="-1"><a class="header-anchor" href="#playground-向けコード" aria-hidden="true">#</a> Playground 向けコード</h3>
<p>Playground でテストコードを書くなら以下のようにするのがスマートかもしれません。</p>
<p>timer は 1 秒おきにカウントを 1 ずつ減らしていくのですが、<code>onTapGesture</code>を使い、どこかがタップされたとき（操作されたとき）にカウントを 10 まで戻すという処理をするのです。</p>
<p>これなら無操作で N 秒（今回の場合は 10 秒）経過した場合に onReceive 内で何らかの操作（スクリーンセーバーを表示する）が可能になるというわけです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">PlaygroundSupport</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> timeRemaining <span class="token operator">=</span> <span class="token number">10</span>
    <span class="token keyword">let</span> timer <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>timeRemaining<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">onReceive</span><span class="token punctuation">(</span>timer<span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token number">_</span> <span class="token keyword">in</span>
                <span class="token keyword">if</span> timeRemaining <span class="token operator">></span> <span class="token number">0</span> <span class="token punctuation">{</span>
                    timeRemaining <span class="token operator">-</span><span class="token operator">=</span> <span class="token number">1</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onTapGesture <span class="token punctuation">{</span>
                timeRemaining <span class="token operator">=</span> <span class="token number">10</span>
            <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token builtin">PlaygroundPage</span><span class="token punctuation">.</span>current<span class="token punctuation">.</span>liveView <span class="token operator">=</span> <span class="token function">UIHostingController</span><span class="token punctuation">(</span>rootView<span class="token punctuation">:</span> <span class="token function">ContentView</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br></div></div><h2 id="timer-combine" tabindex="-1"><a class="header-anchor" href="#timer-combine" aria-hidden="true">#</a> Timer + Combine</h2>
<p>そういえば以前に時計アプリを作りたくて<a href="https://github.com/ivicamil/clock-swiftui-sample" target="_blank" rel="noopener noreferrer">clock-swiftui-sample<OutboundLink/></a>を参考にしたのですが、ここで不思議なタイマーの使い方をしていたことを思い出したのでついでに学習することにしました。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Combine</span>

<span class="token keyword">struct</span> <span class="token builtin">ClockModel</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> hours<span class="token punctuation">:</span> <span class="token builtin">Int</span>
    <span class="token keyword">let</span> minutes<span class="token punctuation">:</span> <span class="token builtin">Int</span>
    <span class="token keyword">let</span> seconds<span class="token punctuation">:</span> <span class="token builtin">Int</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>date<span class="token punctuation">:</span> <span class="token builtin">Date</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> calendar <span class="token operator">=</span> <span class="token builtin">Calendar</span><span class="token punctuation">.</span>current
        <span class="token keyword">let</span> now <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">let</span> hours <span class="token operator">=</span> calendar<span class="token punctuation">.</span><span class="token function">component</span><span class="token punctuation">(</span><span class="token punctuation">.</span>hour<span class="token punctuation">,</span> from<span class="token punctuation">:</span> now<span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>hours <span class="token operator">=</span> hours <span class="token operator">&lt;=</span> <span class="token number">12</span> <span class="token operator">?</span> hours <span class="token punctuation">:</span> hours <span class="token operator">-</span> <span class="token number">12</span>
        minutes <span class="token operator">=</span> calendar<span class="token punctuation">.</span><span class="token function">component</span><span class="token punctuation">(</span><span class="token punctuation">.</span>minute<span class="token punctuation">,</span> from<span class="token punctuation">:</span> now<span class="token punctuation">)</span>
        seconds <span class="token operator">=</span> calendar<span class="token punctuation">.</span><span class="token function">component</span><span class="token punctuation">(</span><span class="token punctuation">.</span>second<span class="token punctuation">,</span> from<span class="token punctuation">:</span> now<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">struct</span> <span class="token builtin">ClockView</span> <span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>

    @<span class="token function">State</span><span class="token punctuation">(</span>initialValue<span class="token punctuation">:</span> <span class="token function">ClockModel</span><span class="token punctuation">(</span>date<span class="token punctuation">:</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> time<span class="token punctuation">:</span> <span class="token builtin">ClockModel</span>

    @<span class="token builtin">State</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> timerSubscription<span class="token punctuation">:</span> <span class="token builtin">Cancellable</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token constant">nil</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> hourPointerBaseRadius<span class="token punctuation">:</span> <span class="token builtin">CGFloat</span> <span class="token operator">=</span> <span class="token number">0.1</span>
    <span class="token keyword">private</span> <span class="token keyword">let</span> secondPointerBaseRadius<span class="token punctuation">:</span> <span class="token builtin">CGFloat</span> <span class="token operator">=</span> <span class="token number">0.05</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">ZStack</span> <span class="token punctuation">{</span>
            <span class="token function">Circle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>primary<span class="token punctuation">)</span>
            <span class="token function">ClockMarks</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token function">ClockIndicator</span><span class="token punctuation">(</span>type<span class="token punctuation">:</span> <span class="token punctuation">.</span>hour<span class="token punctuation">,</span> time<span class="token punctuation">:</span> time<span class="token punctuation">)</span>
            <span class="token function">ClockIndicator</span><span class="token punctuation">(</span>type<span class="token punctuation">:</span> <span class="token punctuation">.</span>minute<span class="token punctuation">,</span> time<span class="token punctuation">:</span> time<span class="token punctuation">)</span>
            <span class="token function">ClockIndicator</span><span class="token punctuation">(</span>type<span class="token punctuation">:</span> <span class="token punctuation">.</span>second<span class="token punctuation">,</span> time<span class="token punctuation">:</span> time<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
        <span class="token punctuation">.</span><span class="token function">padding</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">aspectRatio</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> contentMode<span class="token punctuation">:</span> <span class="token punctuation">.</span>fit<span class="token punctuation">)</span>
        <span class="token punctuation">.</span>onAppear <span class="token punctuation">{</span> <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
        <span class="token punctuation">.</span>onDisappear <span class="token punctuation">{</span> <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        timerSubscription <span class="token operator">=</span>
            <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token builtin">ClockModel</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>time<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        timerSubscription<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br></div></div><p>ここで気になるのは<code>private func subscribe()</code>の内容です。また、Combine をインポートしている点も気になります（単に Timer を使うだけなら Combine は不要のため）</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    timerSubscription <span class="token operator">=</span>
        <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token builtin">ClockModel</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>time<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>このコードの意味が完全に理解できない限り、コーディングを進めることは不可能でしょう。</p>
<p>何故なら、例えば「該当するビューが表示されていない間はスクリーンセーバの判定をしない」というようなコードであってもこのような単純なコードでは Timer が動き続けてしまうことが考えられるからです。</p>
<p>ビューが表示されなくなったら Timer は破棄する、といった柔軟なコードにしたいわけです。</p>
<h3 id="timer-を利用したコード" tabindex="-1"><a class="header-anchor" href="#timer-を利用したコード" aria-hidden="true">#</a> Timer を利用したコード</h3>
<p>単純に Timer を利用しただけのコードが以下になります。</p>
<p>めんどくさかったので Timer が publish している値（Date 型）の description（String 型）をとって表示しただけのものです。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">PlaygroundSupport</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> currentTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> timer <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">Text</span><span class="token punctuation">(</span>currentTime<span class="token punctuation">.</span>description<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">onReceive</span><span class="token punctuation">(</span>timer<span class="token punctuation">)</span> <span class="token punctuation">{</span> value <span class="token keyword">in</span>
                currentTime <span class="token operator">=</span> value<span class="token punctuation">.</span>description
            <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token builtin">PlaygroundPage</span><span class="token punctuation">.</span>current<span class="token punctuation">.</span>liveView <span class="token operator">=</span> <span class="token function">UIHostingController</span><span class="token punctuation">(</span>rootView<span class="token punctuation">:</span> <span class="token function">ContentView</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="combine-を利用したコード" tabindex="-1"><a class="header-anchor" href="#combine-を利用したコード" aria-hidden="true">#</a> Combine を利用したコード</h3>
<p>ではこのコードを Combine を使って書き直すことを考えます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Combine</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> currentTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> cancelable<span class="token punctuation">:</span> <span class="token builtin">AnyCancellable</span><span class="token operator">?</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">Text</span><span class="token punctuation">(</span>currentTime<span class="token punctuation">.</span>description<span class="token punctuation">)</span>
            <span class="token punctuation">.</span>onAppear <span class="token punctuation">{</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onDisappear <span class="token punctuation">{</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancelable <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">receive</span><span class="token punctuation">(</span>on<span class="token punctuation">:</span> <span class="token builtin">DispatchQueue</span><span class="token punctuation">.</span>main<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>currentTime<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancelable<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br></div></div><p><code>receive(on: DispatchQueue.main)</code>はどのスレッドで動作させるかを選択します。全部メインスレッドで実行するとメインスレッドが固まってしまうような場合が考えられるからです。</p>
<p>今回は軽い動作なのでメインスレッドで実行していますが、<code>DispatchQueue.global()</code>などを指定してもよいのではないかと思います。</p>
<p>こちら
](https://qiita.com/shiz/items/9dc8e9a96f399b6c7246)の記事が大変参考になりました。</p>
<p>単純に Timer だけを使うコードに比べて少し長いコードになりましたが、非表示になったときに unsubscribe が呼ばれるので利便性の高いコードになったのではないでしょうか。</p>
<p><code>assign</code>は Timer が publish したデータを受け取る変数を指定します。Timer は Date 型を publish しているので Date 型の変数である<code>currentTime</code>で受け取っています。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">private</span> <span class="token keyword">var</span> time<span class="token punctuation">:</span> <span class="token builtin">ClockModel</span>

<span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    timerSubscription <span class="token operator">=</span>
        <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token builtin">ClockModel</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">)</span> <span class="token comment">// map{ ClockModel($0) }でもOK</span>
        <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>time<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>ここでデモコードを見てみると<code>assign</code>が Date 型ではない ClockModel 型の time に値を渡していることがわかります。なぜこのようなことが可能なのでしょうか。</p>
<p>実はその前の<code>map(ClockModel.init)</code>がカギになっており、ここで本来受け渡されるはずの Date 型を ClockModel 型に変換しているのです。</p>
<p><code>map</code>の本来の使い方を考えれば<code>map{ ClockModel($0) }</code>という書き方が思いつくのですが、これらは同値なのでどちらの書き方でも正しく動作します。</p>
<h2 id="スクリーンセーバを作成する" tabindex="-1"><a class="header-anchor" href="#スクリーンセーバを作成する" aria-hidden="true">#</a> スクリーンセーバを作成する</h2>
<p>ここまでの調査でなんとなく Timer や Combine の使い方がわかったので実際にコードにしてみましょう。</p>
<p>仕組みとしては以下のような感じで実装できます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Combine</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> currentTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> lastTappedTime<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token function">Int</span><span class="token punctuation">(</span><span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>timeIntervalSince1970<span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> screenSaver<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> cancelable<span class="token punctuation">:</span> <span class="token builtin">AnyCancellable</span><span class="token operator">?</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">ClockView</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">150</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">150</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span><span class="token function">Int</span><span class="token punctuation">(</span>screenSaver<span class="token punctuation">.</span>timeIntervalSince1970<span class="token punctuation">)</span> <span class="token operator">>=</span> lastTappedTime <span class="token operator">+</span> <span class="token number">10</span> <span class="token operator">?</span> <span class="token number">0.0</span> <span class="token punctuation">:</span> <span class="token number">1.0</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span>onAppear <span class="token punctuation">{</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onDisappear <span class="token punctuation">{</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onTapGesture <span class="token punctuation">{</span>
                lastTappedTime <span class="token operator">=</span> <span class="token function">Int</span><span class="token punctuation">(</span><span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>timeIntervalSince1970<span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancelable <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">receive</span><span class="token punctuation">(</span>on<span class="token punctuation">:</span> <span class="token builtin">DispatchQueue</span><span class="token punctuation">.</span>main<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>screenSaver<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancelable<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br></div></div><p>最後にタップした時間を<code>lastTappedTime</code>として保存しておき、<code>subscribe()</code>で一秒ごとに<code>screenSaver</code>の中身を更新し、それの timestamp を求めて lastTappedTime よりも 10 秒以上経過していたら透明度を変更して<code>ClockView()</code>を表示させるような内容になっています。</p>
<p>最初は lastTappedTime を持つ構造体をつくってそれにマッピングしようかとも思ったのですが毎回初期化されてしまうため意味がありませんでした。</p>
<p>上のコードをそれっぽく直したものが以下のものになります。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Combine</span>

<span class="token keyword">struct</span> <span class="token builtin">ScreenSaver</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> opacity<span class="token punctuation">:</span> <span class="token builtin">Double</span> <span class="token operator">=</span> <span class="token number">0.0</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>from date<span class="token punctuation">:</span> <span class="token builtin">Date</span><span class="token punctuation">,</span> lastTappedTime<span class="token punctuation">:</span> <span class="token builtin">Date</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> date<span class="token punctuation">.</span>timeIntervalSince1970 <span class="token operator">>=</span> lastTappedTime<span class="token punctuation">.</span>timeIntervalSince1970 <span class="token operator">+</span> <span class="token number">10</span> <span class="token punctuation">{</span>
            withAnimation <span class="token punctuation">{</span>
                opacity <span class="token operator">=</span> <span class="token number">1.0</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> currentTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> cancellable<span class="token punctuation">:</span> <span class="token builtin">AnyCancellable</span><span class="token operator">?</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> lastTappedTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> screenSaver<span class="token punctuation">:</span> <span class="token builtin">ScreenSaver</span> <span class="token operator">=</span> <span class="token function">ScreenSaver</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> cancelable<span class="token punctuation">:</span> <span class="token builtin">AnyCancellable</span><span class="token operator">?</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token function">ClockView</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> <span class="token number">150</span><span class="token punctuation">,</span> height<span class="token punctuation">:</span> <span class="token number">150</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span>screenSaver<span class="token punctuation">.</span>opacity<span class="token punctuation">)</span>
            <span class="token punctuation">.</span>onAppear <span class="token punctuation">{</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onDisappear <span class="token punctuation">{</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
            <span class="token punctuation">.</span>onTapGesture <span class="token punctuation">{</span>
                lastTappedTime <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancellable <span class="token operator">=</span> <span class="token builtin">Timer</span><span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>every<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token punctuation">.</span>main<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>common<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">autoconnect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">receive</span><span class="token punctuation">(</span>on<span class="token punctuation">:</span> <span class="token builtin">DispatchQueue</span><span class="token punctuation">.</span>main<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token builtin">map</span><span class="token punctuation">{</span> <span class="token function">ScreenSaver</span><span class="token punctuation">(</span>from<span class="token punctuation">:</span> $<span class="token number">0</span><span class="token punctuation">,</span> lastTappedTime<span class="token punctuation">:</span> lastTappedTime<span class="token punctuation">)</span><span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> \<span class="token punctuation">.</span>screenSaver<span class="token punctuation">,</span> on<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">unsubscribe</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        cancellable<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">cancel</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br></div></div><p>ScreenSaver の構造体が引数からビューを非表示にするかどうかの変数<code>opacity</code>を計算してくれるわけです。</p>
<p>が、よく考えたらこれは普通に computed property でもいいのではないかという気がしてきました。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ScreenSaver</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> date<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> lastTappedTime<span class="token punctuation">:</span> <span class="token builtin">Date</span> <span class="token operator">=</span> <span class="token function">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">var</span> opacity<span class="token punctuation">:</span> <span class="token builtin">Double</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> date<span class="token punctuation">.</span>timeIntervalSince1970 <span class="token operator">>=</span> lastTappedTime<span class="token punctuation">.</span>timeIntervalSince1970 <span class="token operator">+</span> <span class="token number">10</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token number">1.0</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token number">0.0</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span>from date<span class="token punctuation">:</span> <span class="token builtin">Date</span><span class="token punctuation">,</span> lastTappedTime<span class="token punctuation">:</span> <span class="token builtin">Date</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>date <span class="token operator">=</span> date
        <span class="token keyword">self</span><span class="token punctuation">.</span>lastTappedTime <span class="token operator">=</span> lastTappedTime
    <span class="token punctuation">}</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><p>つまり、こう書けるということなのですがこうなってしまうとわざわざ構造体にマッピングする必要があったのかという疑問が生じます。</p>
<p>動作こそするものの、もっと上手な書き方がある気がしますね。</p>
<h2 id="使ってみた感想" tabindex="-1"><a class="header-anchor" href="#使ってみた感想" aria-hidden="true">#</a> 使ってみた感想</h2>
<p>Timer の方が実装が楽である反面、Combine を使った方法の方がコードとしてはしっくりきている印象を受けた。</p>
<p>ただ、<a href="https://developer.apple.com/documentation/combine/fail/receive(on:options:)" target="_blank" rel="noopener noreferrer"><code>receive(on: Publisher)</code><OutboundLink/></a>の仕組みをしっかりと理解できていないためもやもやが残っていないかと言われると嘘になる。</p>
</template>
