<template><h1 id="collectionview" tabindex="-1"><a class="header-anchor" href="#collectionview" aria-hidden="true">#</a> CollectionView</h1>
<p>CollectionView は UiKit では実装されていたものの、SwiftUI では消されてしまった悲しき存在の一つ。</p>
<p>ですが、SwiftUI2.0 で<code>LazyHGrid</code>が実装されたことによりそれっぽく CollectionView をつくることができるようになりました。</p>
<h2 id="実装してみる" tabindex="-1"><a class="header-anchor" href="#実装してみる" aria-hidden="true">#</a> 実装してみる</h2>
<p>実装にあたり<a href="https://qiita.com/yuki_m/items/b2ee2f93e1eb94aaf079" target="_blank" rel="noopener noreferrer">こちらの記事<OutboundLink/></a>を参考にさせていただきました。</p>
<h3 id="主な仕様" tabindex="-1"><a class="header-anchor" href="#主な仕様" aria-hidden="true">#</a> 主な仕様</h3>
<ul>
<li>iOS14 のみで動作
<ul>
<li><code>LazyHGrid</code>が iOS13 では実装されていないため</li>
</ul>
</li>
<li>全てのページは同じ横幅を持つ
<ul>
<li>読書アプリのようなものを想定</li>
<li>サイズが違う場合は参考ページのように<code>resizable()</code>を使えば良いと思います</li>
</ul>
</li>
<li>画面を回転させた場合でも常に中央に表示される
<ul>
<li>参考ページのコードでは回転時にレイアウトが崩れてしまうのでそれを修正しました</li>
</ul>
</li>
</ul>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// ScrollViewのExtension</span>
<span class="token keyword">extension</span> <span class="token builtin">ScrollView</span> <span class="token punctuation">{</span>
    <span class="token keyword">func</span> <span class="token function">paging</span><span class="token punctuation">(</span>geometry<span class="token punctuation">:</span> <span class="token builtin">GeometryProxy</span><span class="token punctuation">,</span> index<span class="token punctuation">:</span> <span class="token builtin">Binding</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">,</span> offset<span class="token punctuation">:</span> <span class="token builtin">Binding</span><span class="token operator">&lt;</span><span class="token builtin">CGFloat</span><span class="token operator">></span><span class="token punctuation">,</span> orientation<span class="token punctuation">:</span> <span class="token builtin">Binding</span><span class="token operator">&lt;</span><span class="token builtin">UIInterfaceOrientation</span><span class="token operator">></span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token keyword">self</span>
            <span class="token punctuation">.</span>content<span class="token punctuation">.</span><span class="token function">offset</span><span class="token punctuation">(</span>x<span class="token punctuation">:</span> offset<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">onReceive</span><span class="token punctuation">(</span><span class="token builtin">NotificationCenter</span><span class="token punctuation">.</span><span class="token keyword">default</span><span class="token punctuation">.</span><span class="token function">publisher</span><span class="token punctuation">(</span><span class="token keyword">for</span><span class="token punctuation">:</span> <span class="token builtin">UIDevice</span><span class="token punctuation">.</span>orientationDidChangeNotification<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token number">_</span> <span class="token keyword">in</span>
                <span class="token keyword">guard</span> <span class="token keyword">let</span> status <span class="token operator">=</span> <span class="token builtin">UIApplication</span><span class="token punctuation">.</span>shared<span class="token punctuation">.</span>windows<span class="token punctuation">.</span><span class="token builtin">first</span><span class="token operator">?</span><span class="token punctuation">.</span>windowScene<span class="token operator">?</span><span class="token punctuation">.</span>interfaceOrientation <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
                <span class="token keyword">if</span> <span class="token operator">!</span><span class="token builtin">UIDevice</span><span class="token punctuation">.</span>current<span class="token punctuation">.</span>orientation<span class="token punctuation">.</span>isFlat <span class="token punctuation">{</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>orientation<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">.</span>isPortrait <span class="token operator">!=</span> status<span class="token punctuation">.</span>isPortrait<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token punctuation">(</span>orientation<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">.</span>isLandscape <span class="token operator">!=</span> status<span class="token punctuation">.</span>isLandscape<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        offset<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token operator">-</span><span class="token punctuation">(</span>geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>height <span class="token operator">+</span> <span class="token punctuation">(</span><span class="token builtin">UIApplication</span><span class="token punctuation">.</span>shared<span class="token punctuation">.</span>windows<span class="token punctuation">.</span><span class="token builtin">first</span><span class="token operator">?</span><span class="token punctuation">.</span>windowScene<span class="token operator">?</span><span class="token punctuation">.</span>statusBarManager<span class="token operator">?</span><span class="token punctuation">.</span>statusBarFrame<span class="token punctuation">.</span>height <span class="token operator">?</span><span class="token operator">?</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token function">CGFloat</span><span class="token punctuation">(</span>index<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span>
                        orientation<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> status
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">gesture</span><span class="token punctuation">(</span><span class="token function">DragGesture</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">onChanged</span><span class="token punctuation">(</span><span class="token punctuation">{</span> value <span class="token keyword">in</span>
                            offset<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> value<span class="token punctuation">.</span>translation<span class="token punctuation">.</span>width <span class="token operator">-</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>width <span class="token operator">*</span> <span class="token function">CGFloat</span><span class="token punctuation">(</span>index<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span>
                        <span class="token punctuation">}</span><span class="token punctuation">)</span>
                        <span class="token punctuation">.</span><span class="token function">onEnded</span><span class="token punctuation">(</span><span class="token punctuation">{</span> value <span class="token keyword">in</span>
                            <span class="token keyword">let</span> scrollThreshold <span class="token operator">=</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>width <span class="token operator">/</span> <span class="token number">2</span>
                            <span class="token keyword">if</span> value<span class="token punctuation">.</span>predictedEndTranslation<span class="token punctuation">.</span>width <span class="token operator">&lt;</span> <span class="token operator">-</span>scrollThreshold <span class="token punctuation">{</span>
                                index<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token function">min</span><span class="token punctuation">(</span>index<span class="token punctuation">.</span>wrappedValue <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">)</span>
                            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> value<span class="token punctuation">.</span>predictedEndTranslation<span class="token punctuation">.</span>width <span class="token operator">></span> scrollThreshold <span class="token punctuation">{</span>
                                index<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token function">max</span><span class="token punctuation">(</span>index<span class="token punctuation">.</span>wrappedValue <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span>
                            <span class="token punctuation">}</span>
                            withAnimation <span class="token punctuation">{</span>
                                offset<span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token operator">-</span>geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>width <span class="token operator">*</span> <span class="token function">CGFloat</span><span class="token punctuation">(</span>index<span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span>
                            <span class="token punctuation">}</span>
                        <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br></div></div><p>画面の回転に対応させるのがやたらとめんどくさかったです。要するに、<code>Portrait-&gt;Landscape</code>または<code>Landscape-&gt;Portrait</code>時にオフセットを再計算すればよいのですが、これを実装するためには「以前の状態」を保持しておく必要があります。</p>
<p><code>paging()</code>内でもできるかもしれないのですが、わからなかったので今回は割愛してバカ正直に<code>@State</code>で保存するようにしました。</p>
<p>これで 180 度回転を含むどんな回転をさせてもちゃんと画面の中央に表示されます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>

<span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> index<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> offset<span class="token punctuation">:</span> <span class="token builtin">CGFloat</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span> <span class="token keyword">var</span> orientation<span class="token punctuation">:</span> <span class="token builtin">UIInterfaceOrientation</span> <span class="token operator">=</span> <span class="token punctuation">.</span>portrait

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">GeometryReader</span> <span class="token punctuation">{</span> geometry <span class="token keyword">in</span>
            <span class="token function">ScrollView</span><span class="token punctuation">(</span><span class="token punctuation">.</span>horizontal<span class="token punctuation">,</span> showsIndicators<span class="token punctuation">:</span> <span class="token boolean">false</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">LazyHGrid</span><span class="token punctuation">(</span>rows<span class="token punctuation">:</span> <span class="token function">Array</span><span class="token punctuation">(</span>repeating<span class="token punctuation">:</span> <span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">.</span><span class="token function">fixed</span><span class="token punctuation">(</span>geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>height<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token builtin">count</span><span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">,</span> spacing<span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">,</span> pinnedViews<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token function">ForEach</span><span class="token punctuation">(</span><span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> index <span class="token keyword">in</span>
                        <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>index<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
                            <span class="token punctuation">.</span><span class="token function">frame</span><span class="token punctuation">(</span>width<span class="token punctuation">:</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>width<span class="token punctuation">,</span> height<span class="token punctuation">:</span> geometry<span class="token punctuation">.</span>size<span class="token punctuation">.</span>height<span class="token punctuation">,</span> alignment<span class="token punctuation">:</span> <span class="token punctuation">.</span>center<span class="token punctuation">)</span>
                            <span class="token punctuation">.</span><span class="token function">background</span><span class="token punctuation">(</span><span class="token builtin">Color</span><span class="token punctuation">.</span>red<span class="token punctuation">.</span><span class="token function">opacity</span><span class="token punctuation">(</span><span class="token number">0.3</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">edgesIgnoringSafeArea</span><span class="token punctuation">(</span><span class="token punctuation">.</span>all<span class="token punctuation">)</span><span class="token punctuation">)</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">paging</span><span class="token punctuation">(</span>geometry<span class="token punctuation">:</span> geometry<span class="token punctuation">,</span> index<span class="token punctuation">:</span> $index<span class="token punctuation">,</span> offset<span class="token punctuation">:</span> $offset<span class="token punctuation">,</span> orientation<span class="token punctuation">:</span> orientation<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div><div class="custom-container tip"><p class="custom-container-title">謎のオフセット 20 が入る現象</p>
<p>Notification が呼ばれた段階ではステータスバーの高さが無視されているのか、常に 20 だけ<code>geometry.size</code>がズレてしまう問題があった。</p>
<p>そのため、わざわざステータスバーの高さを取得してその分だけ余計に計算している。が、ステータスーバーを非表示にしていたらなんかズレそうな気もする。</p>
</div>
<p>記事は以上。</p>
</template>
