<template><h1 id="documents-にデータを保存する意味" tabindex="-1"><a class="header-anchor" href="#documents-にデータを保存する意味" aria-hidden="true">#</a> Documents にデータを保存する意味</h1>
<p>アプリには三つのコンテナがあり、それぞれ<code>Bundle Container</code>、<code>Data Container</code>、<code>iCloud Container</code>と呼ばれています。</p>
<p>この中で iTunes でバックアップできるのは<code>Data Container</code>になり、<code>Data Container</code>には「Documents」「Library」「Temp」の三つのディレクトリが存在しています。どこのフォルダに何を保存するかはガイドラインで決まっているので、それに従う必要があります。</p>
<h2 id="documents" tabindex="-1"><a class="header-anchor" href="#documents" aria-hidden="true">#</a> Documents</h2>
<div class="custom-container tip"><p class="custom-container-title">Documents について</p>
<p>ユーザーが生成したデータを保存するために使います。ファイル共有の機能により、ユーザーはこのディレクトリ以下にアクセスできます。したがって、ユーザーに見せても構わないファイルのみ置いてください。
iTunes および iCloud はこのディレクトリの内容をバックアップします。</p>
</div>
<h2 id="library" tabindex="-1"><a class="header-anchor" href="#library" aria-hidden="true">#</a> Library</h2>
<div class="custom-container tip"><p class="custom-container-title">Library について</p>
<p>これは、ユーザーのデータファイル以外のファイル用の最上位ディレクトリです。通常、標準的なサブディレクトリを用意し、いずれか適当な場所に保存します。iOS アプリケーションは通常、Application Support および Caches というサブディレクトリを使いますが、独自のサブディレクトリを作成しても構いません。</p>
<p>ユーザーに見せたくないファイルは Library サブディレクトリ以下に置いてください。ユーザーデータのファイル保存用に使ってはなりません。</p>
<p>Library ディレクトリの内容は iTunes および iCloud によってバックアップされます（ただし、Caches サブディレクトリは除く）</p>
</div>
<h2 id="temp" tabindex="-1"><a class="header-anchor" href="#temp" aria-hidden="true">#</a> Temp</h2>
<div class="custom-container tip"><p class="custom-container-title">Temp について</p>
<p>このディレクトリは、アプリケーションを次に起動するまで保持する必要のない一時ファイルを書き込むために使用します。不要になったファイルは削除しなければなりません。もっとも、アプリケーションが動作していないときに、システムがこのディレクトリ以下をすべて消去することがあります。
iTunes または iCloud はこのディレクトリの内容をバックアップしません。</p>
</div>
<h2 id="documents-ディレクトリ" tabindex="-1"><a class="header-anchor" href="#documents-ディレクトリ" aria-hidden="true">#</a> Documents ディレクトリ</h2>
<p>Documents ディレクトリにアクセスしようとしたら、まずパスがわからないといけません。</p>
<p>パスは<code>String</code>か<code>URL</code>で取得することが多いと思うのですが、結論から言えば<code>URL</code>で取得したほうが絶対に楽です。特に制限がなければ<code>URL</code>で取得するようにしましょう。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">private</span> <span class="token keyword">var</span> documentDirectoryFileURL<span class="token punctuation">:</span> <span class="token constant">URL</span> <span class="token operator">=</span> <span class="token builtin">FileManager</span><span class="token punctuation">.</span><span class="token keyword">default</span><span class="token punctuation">.</span><span class="token function">urls</span><span class="token punctuation">(</span><span class="token keyword">for</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>documentDirectory<span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>userDomainMask<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span>
<span class="token keyword">private</span> <span class="token keyword">var</span> documentDirectoryFilePath<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token function">NSSearchPathForDirectoriesInDomains</span><span class="token punctuation">(</span><span class="token punctuation">.</span>documentDirectory<span class="token punctuation">,</span> <span class="token punctuation">.</span>userDomainMask<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>URL の場合と String の場合で微妙に取得方法が違うのが面白いですね。これで非オプショナルなパスを取得することができます。</p>
<h3 id="サブディレクトリ" tabindex="-1"><a class="header-anchor" href="#サブディレクトリ" aria-hidden="true">#</a> サブディレクトリ</h3>
<p>とはいえ、Documents 直下にファイルをガンガン保存することも少ないと思います。サブディレクトリを作成し、その中にファイルを保存したいという方が多いのではないでしょうか。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> path <span class="token operator">=</span> documentDirectoryFileURL<span class="token punctuation">.</span><span class="token function">appendingPathComponent</span><span class="token punctuation">(</span><span class="token string">"JSON"</span><span class="token punctuation">,</span> isDirectory<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span>
<span class="token keyword">do</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> <span class="token builtin">FileManager</span><span class="token punctuation">.</span><span class="token keyword">default</span><span class="token punctuation">.</span><span class="token function">createDirectory</span><span class="token punctuation">(</span>at<span class="token punctuation">:</span> path<span class="token punctuation">,</span> withIntermediateDirectories<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> attributes<span class="token punctuation">:</span> <span class="token constant">nil</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span><span class="token punctuation">(</span><span class="token keyword">let</span> error<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">print</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>というわけで、今回は Documents 下に JSON というフォルダを作成します。作成できなかった場合はとりあえずエラーを表示していますが、ここは各自ななんか適当な処理を入れてください。<code>withIntermediateDirectories</code>というオプションに<code>true</code>を入れておけば中間ディレクトリも自動で作成してくれるので便利です。</p>
<h3 id="データ書き込み" tabindex="-1"><a class="header-anchor" href="#データ書き込み" aria-hidden="true">#</a> データ書き込み</h3>
<p>画像の場合は以下のように Data 型に変換して保存します。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// 画像書き込み</span>
<span class="token keyword">let</span> uiimage<span class="token punctuation">:</span> <span class="token builtin">UIImage</span> <span class="token operator">=</span> <span class="token function">UIImage</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// なんか適当なUIImageを取得</span>
<span class="token keyword">let</span> image<span class="token punctuation">:</span> <span class="token builtin">Data</span> <span class="token operator">=</span> uiimage<span class="token punctuation">.</span><span class="token function">jpegData</span><span class="token punctuation">(</span>compressionQuality<span class="token punctuation">:</span> <span class="token number">0.7</span><span class="token punctuation">)</span><span class="token operator">!</span> <span class="token comment">// Data型に変換</span>
<span class="token keyword">let</span> filePath<span class="token punctuation">:</span> <span class="token constant">URL</span> <span class="token operator">=</span> documentDirectoryFileURL<span class="token punctuation">.</span><span class="token function">appendingPathComponent</span><span class="token punctuation">(</span><span class="token string">"JSON/default.jpeg"</span><span class="token punctuation">)</span>
<span class="token keyword">do</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> image<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> filePath<span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span><span class="token punctuation">(</span><span class="token keyword">let</span> error<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">print</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>今回は JPEG で保存していますが、PNG で保存したい場合は<code>let image: Data = uiimage.pngData()!</code>とすれば良いです。</p>
<p>テキストの場合は<code>String</code>であれば標準の書き込みライブラリである<code>write</code>が利用できます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// テキスト書き込み</span>
<span class="token keyword">let</span> text<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token string">"Hello, world!"</span>
<span class="token keyword">let</span> filePath<span class="token punctuation">:</span> <span class="token constant">URL</span> <span class="token operator">=</span> documentDirectoryFileURL<span class="token punctuation">.</span><span class="token function">appendingPathComponent</span><span class="token punctuation">(</span><span class="token string">"JSON/default.txt"</span><span class="token punctuation">)</span>
<span class="token keyword">do</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> text<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> filePath<span class="token punctuation">,</span> atomically<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> encoding<span class="token punctuation">:</span> <span class="token punctuation">.</span>utf8<span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span><span class="token punctuation">(</span><span class="token keyword">let</span> error<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">print</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p><code>atomically</code>オプションは一時フォルダに書き込みを行い、成功すれば指定されたディレクトリにコピーするための保険のようなものです。エンコーディングは特に制限がなければ<code>.utf8</code>を利用するのがいいでしょう。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// JSON書き込み</span>
<span class="token keyword">let</span> json<span class="token punctuation">:</span> <span class="token constant">JSON</span> <span class="token operator">=</span> <span class="token function">JSON</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">let</span> jsonString<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> json<span class="token punctuation">.</span>description<span class="token punctuation">.</span><span class="token function">data</span><span class="token punctuation">(</span>using<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">.</span><span class="token builtin">Encoding</span><span class="token punctuation">.</span>utf8<span class="token punctuation">)</span><span class="token operator">!</span>
<span class="token keyword">let</span> filePath<span class="token punctuation">:</span> <span class="token constant">URL</span> <span class="token operator">=</span> documentDirectoryFileURL<span class="token punctuation">.</span><span class="token function">appendingPathComponent</span><span class="token punctuation">(</span><span class="token string">"JSON/default.json"</span><span class="token punctuation">)</span>
<span class="token keyword">do</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> jsonString<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>to<span class="token punctuation">:</span> filePath<span class="token punctuation">,</span> atomically<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> encoding<span class="token punctuation">:</span> <span class="token punctuation">.</span>utf8<span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span><span class="token punctuation">(</span><span class="token keyword">let</span> error<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">print</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>JSON は結局テキストファイルなのでテキストと同じ書き込み方法が使えます。<a href="https://github.com/SwiftyJSON/SwiftyJSON" target="_blank" rel="noopener noreferrer">SwiftyJSON<OutboundLink/></a>であれば上のコードで JSON を String に変換できるのでそれが一番手っ取り早いです。</p>
</template>
