<template><h2 id="theos-jailed" tabindex="-1"><a class="header-anchor" href="#theos-jailed" aria-hidden="true">#</a> THEOS JAILED</h2>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token operator">=</span> 必要なもの <span class="token operator">=</span>
<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token number">1</span>. 忍耐力と運
<span class="token number">2</span>. XcodeとiOS SDK
<span class="token number">3</span>. Clutchなどで復号されたipaファイル

<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token operator">=</span> プロビジョニングプロファイルの作成 <span class="token operator">=</span>
<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
注意: このステップは一つのアプリに対して一度実行するだけで良い. もしワイルドカード
     のプロファイルがある場合はこのステップをとばして構わない.
<span class="token number">1</span>. Xcodeをひらき、新規プロジェクトを作成.
<span class="token number">2</span>. iOSを選択し, Single View Applicationを選ぶ.
<span class="token number">3</span>. プロダクト名として<span class="token operator">&lt;</span>PRODUCT NAME<span class="token operator">></span>を利用する.
<span class="token number">4</span>. Organization Identifierとして<span class="token operator">&lt;</span>ORGANIZATION IDENTIFIER<span class="token operator">></span>を設定する.
<span class="token number">5</span>. Nextを押してプロジェクトを保存. Gitのチェックは外しておくこと.
<span class="token number">6</span>. デバイスをMacに接続してアプリをビルドする. さまざまな警告はのちのち解決するので
   現段階では無視して良い.
<span class="token number">7</span>. Deployment Info内のDeployment Targetを自身のデバイスに合わせる.
<span class="token number">8</span>. Signingで自分のAppleIDを選択する
<span class="token number">9</span>. Fix Issueを押す. この段階でプロビジョニングプロファイルが自動で作成される.
<span class="token number">10</span>. Generalタブの右のCapabilitiesを選択する.
<span class="token number">11</span>. App Groupsを有効化する.

<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token operator">=</span> プロビジョニングプロファイルのインストール <span class="token operator">=</span>
<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token number">1</span>. Runを押してアプリをインストールする.
<span class="token number">2</span>. アプリがインストールして起動を確認したらアプリを削除する.
<span class="token number">3</span>. Xcodeを終了する
注意: このステップは一つのアプリに対して一度実行するだけで良い

<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token operator">=</span> ios-deployでインストールする <span class="token operator">=</span>
<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span>
<span class="token number">1</span>. Run <span class="token function">make</span> package <span class="token function">install</span> <span class="token assign-left variable">PROFILE</span><span class="token operator">=</span>ID-5A701E68.work.tkgstrator.ikawidget2adkiller
   Note: If you omit the <span class="token assign-left variable">PROFILE</span><span class="token operator">=</span>… part, the script will try to use
         Xcode iOS Wildcard App ID. This will only work <span class="token keyword">if</span> you are enrolled
         <span class="token keyword">in</span> the Apple Developer Program.
<span class="token number">2</span>. If you get an error during installation, use the following method:

<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">=</span>
<span class="token operator">=</span> Xcodeでインストールする <span class="token operator">=</span>
<span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">==</span><span class="token operator">=</span>
<span class="token number">1</span>. XcodeのタブからDeviceを選択する.
<span class="token number">2</span>. Installed Appsの下の+をクリックする.
<span class="token number">3</span>. パッチを当てたipaを選択し, 神に祈る.
<span class="token number">4</span>. パッチを当てたipaがデバイス上に表示される
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br></div></div></template>
