<template><h1 id="realmswift" tabindex="-1"><a class="header-anchor" href="#realmswift" aria-hidden="true">#</a> <a href="https://github.com/realm/realm-cocoa" target="_blank" rel="noopener noreferrer">RealmSwift<OutboundLink/></a></h1>
<p>RealmSwift が<a href="https://github.com/realm/realm-cocoa/releases/tag/v10.10.0" target="_blank" rel="noopener noreferrer">10.10.0<OutboundLink/></a>にアップデートされて大幅な変更が入っていました。</p>
<h2 id="realmswift-10-10-0" tabindex="-1"><a class="header-anchor" href="#realmswift-10-10-0" aria-hidden="true">#</a> RealmSwift 10.10.0</h2>
<h3 id="新規機能" tabindex="-1"><a class="header-anchor" href="#新規機能" aria-hidden="true">#</a> 新規機能</h3>
<ul>
<li>全てのプロパティが同一の方法で宣言できる</li>
<li>プライマリキーの設定が簡単になった</li>
<li>リストも簡単に宣言できる</li>
<li><code>RawRepresentable</code>が<code>@Persisted</code>に対応している型であれば Enum も保存できる</li>
<li><code>Map.merge()</code>が実装され、辞書形式ペアを他の<code>Map</code>や<code>Dictionary</code>に変換できるようになった</li>
<li><code>Map.asKeyValueSequence()</code>が実装され、辞書形式の配列を返すようになった</li>
</ul>
<h3 id="バグ修正" tabindex="-1"><a class="header-anchor" href="#バグ修正" aria-hidden="true">#</a> バグ修正</h3>
<ul>
<li>より多くの Enum オブジェクトをサポート</li>
<li><code>RealmProperty&lt;AnyRealmValue?&gt;</code>を宣言するとエラーを返す問題</li>
<li><code>KVO</code>を経由して<code>RLMDictionary/Map</code>の<code>Invalidated</code>の通知が正しく設定されない問題</li>
</ul>
<h2 id="使い方" tabindex="-1"><a class="header-anchor" href="#使い方" aria-hidden="true">#</a> 使い方</h2>
<p>全てのプロパティを<code>@Persisted</code>で宣言できるのはとても便利。もっと早くコレに対応すべきだったのでは。</p>
<h3 id="旧コード" tabindex="-1"><a class="header-anchor" href="#旧コード" aria-hidden="true">#</a> 旧コード</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// Legacy</span>
<span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    <span class="token atrule">@objc</span> <span class="token keyword">dynamic</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>       <span class="token comment">// Int</span>
    <span class="token keyword">let</span> age <span class="token operator">=</span> <span class="token builtin">RealmOptional</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token number">0</span>  <span class="token comment">// RealmOptional&lt;Int></span>
    <span class="token keyword">let</span> age <span class="token operator">=</span> <span class="token builtin">RealmProperty</span><span class="token operator">&lt;</span><span class="token builtin">Int</span><span class="token operator">?</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token number">0</span> <span class="token comment">// RealmProperty&lt;Int?></span>

    <span class="token comment">// Primary Key</span>
    <span class="token keyword">override</span> <span class="token keyword">static</span> <span class="token keyword">func</span> <span class="token function">primaryKey</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">String</span><span class="token operator">?</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"id"</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="新コード" tabindex="-1"><a class="header-anchor" href="#新コード" aria-hidden="true">#</a> 新コード</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token comment">// Modern</span>
<span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>      <span class="token comment">// Int</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> age<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token number">0</span>    <span class="token comment">// Int?</span>

    <span class="token comment">// Primary Key</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>primaryKey<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span> userId<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>indexed<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span> point<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    <span class="token comment">// Enum</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> userType<span class="token punctuation">:</span> <span class="token builtin">UserType</span> <span class="token operator">=</span> <span class="token punctuation">.</span>standard
<span class="token punctuation">}</span>

<span class="token keyword">enum</span> <span class="token builtin">UserType</span><span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token punctuation">,</span> <span class="token builtin">PersitableEnum</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> standard   <span class="token operator">=</span> <span class="token number">0</span>
    <span class="token keyword">case</span> unlimited  <span class="token operator">=</span> <span class="token number">1</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><h3 id="linkingobjects" tabindex="-1"><a class="header-anchor" href="#linkingobjects" aria-hidden="true">#</a> LinkingObjects</h3>
<p><code>LinkingObjects</code>はちょっと書き方が変わっていました。ドキュメントも古いままなのでわからなかったのですが、テストコードを読んでようやく意味を理解。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span><span class="token punctuation">{</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> cats<span class="token punctuation">:</span> <span class="token builtin">List</span><span class="token operator">&lt;</span><span class="token builtin">Cat</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token builtin">List</span><span class="token operator">&lt;</span><span class="token builtin">Cat</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">super</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>cats<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token function">Cat</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token string">"Mike"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">class</span> <span class="token class-name">Cat</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> name<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token string">""</span>

    <span class="token comment">// Legacy</span>
    <span class="token keyword">let</span> owner <span class="token operator">=</span> <span class="token function">LinkingObjects</span><span class="token punctuation">(</span>fromType<span class="token punctuation">:</span> <span class="token builtin">User</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">,</span> property<span class="token punctuation">:</span> <span class="token string">"cats"</span><span class="token punctuation">)</span>

    <span class="token comment">// Modern</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>originProperty<span class="token punctuation">:</span> <span class="token string">"cats"</span><span class="token punctuation">)</span> <span class="token keyword">var</span> owner<span class="token punctuation">:</span> <span class="token builtin">LinkingObjects</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span>

    <span class="token comment">// Convenience</span>
    <span class="token keyword">convenience</span> <span class="token keyword">init</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br></div></div><div class="custom-container warning"><p class="custom-container-title">イニシャライザ</p>
<p>引数を取るイニシャライザを定義した場合、<code>convenience</code>と<code>self.init()</code>を書かないと実行時にエラーが発生します。</p>
</div>
<p><code>LinkingObject</code>をたどるためには、</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> owner <span class="token operator">=</span> cat<span class="token punctuation">.</span>owner<span class="token punctuation">.</span><span class="token builtin">first</span><span class="token operator">!</span>
<span class="token keyword">guard</span> <span class="token keyword">let</span> owner <span class="token operator">=</span> cat<span class="token punctuation">.</span>owner<span class="token punctuation">.</span><span class="token builtin">first</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>のようにしてアクセスすれば良い。しかし、バックリンクは一つしかないはずなのに何故<code>first</code>が必要なのかがわからない。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token builtin">LinkingObjects</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span> <span class="token operator">&lt;</span><span class="token number">0x7f9da952a1a0</span><span class="token operator">></span> <span class="token punctuation">(</span>
	<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token builtin">User</span> <span class="token punctuation">{</span>
		id <span class="token operator">=</span> <span class="token number">27</span><span class="token punctuation">;</span>
		age <span class="token operator">=</span> <span class="token number">43</span><span class="token punctuation">;</span>
		cats <span class="token operator">=</span> <span class="token builtin">List</span><span class="token operator">&lt;</span><span class="token builtin">Cat</span><span class="token operator">></span> <span class="token operator">&lt;</span><span class="token number">0x600001d9d290</span><span class="token operator">></span> <span class="token punctuation">(</span>
			<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token builtin">Cat</span> <span class="token punctuation">{</span>
				age <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
				name <span class="token operator">=</span> <span class="token builtin">Mike</span><span class="token punctuation">;</span>
			<span class="token punctuation">}</span>
		<span class="token punctuation">)</span><span class="token punctuation">;</span>
		userType <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>ちなみに<code>LinkingObject</code>自体は参照すると上のようなデータを持っていたので、やはり<code>[0]</code>番目にアクセスするには<code>first</code>とつけなければいけないようだ。</p>
<h3 id="疑問点" tabindex="-1"><a class="header-anchor" href="#疑問点" aria-hidden="true">#</a> 疑問点</h3>
<p>以下のプロパティは使い方がいまいちわからなかった。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>@<span class="token function">Persisted</span><span class="token punctuation">(</span>wrappedValue<span class="token punctuation">:</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span>
@<span class="token builtin">Persisted</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">100</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>この二つ、ほとんど同じように感じますし、実際に実行するとどちらも初期値 100 で初期化されています。</p>
<h3 id="注意点" tabindex="-1"><a class="header-anchor" href="#注意点" aria-hidden="true">#</a> 注意点</h3>
<p>単にクラスを定義するだけなら以下のように書けます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>primaryKey<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> age<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token number">0</span>

    <span class="token comment">// Override</span>
    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>id <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>age <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>イニシャライザを<code>override</code>しなければいけないことだけ忘れないように。</p>
<p><code>RealmSwift.List</code>を定義するとちょっとだけややこしくなります。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>primaryKey<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> age<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> cats<span class="token punctuation">:</span> <span class="token builtin">List</span><span class="token operator">&lt;</span><span class="token builtin">Cat</span><span class="token operator">></span>

    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>id <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>age <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>cats<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token function">Cat</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token string">"Mike"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">class</span> <span class="token class-name">Cat</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> name<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token string">""</span>

    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><p>こうすると初期化されていない<code>cats</code>に値を代入しようとしているとエラーが出ます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token function">Persisted</span><span class="token punctuation">(</span>primaryKey<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span> <span class="token keyword">var</span> id<span class="token punctuation">:</span> <span class="token builtin">Int</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> age<span class="token punctuation">:</span> <span class="token builtin">Int</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token number">0</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> cats<span class="token punctuation">:</span> <span class="token builtin">List</span><span class="token operator">&lt;</span><span class="token builtin">Cat</span><span class="token operator">></span>

    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">super</span><span class="token punctuation">.</span><span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>    <span class="token comment">// Required</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>id <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>age <span class="token operator">=</span> <span class="token builtin">Int</span><span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token keyword">in</span><span class="token punctuation">:</span> <span class="token function">Range</span><span class="token punctuation">(</span><span class="token number">0</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>cats<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token function">Cat</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token string">"Mike"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">class</span> <span class="token class-name">Cat</span><span class="token punctuation">:</span> <span class="token builtin">Object</span> <span class="token punctuation">{</span>
    @<span class="token builtin">Persisted</span> <span class="token keyword">var</span> name<span class="token punctuation">:</span> <span class="token builtin">String</span> <span class="token operator">=</span> <span class="token string">""</span>

    <span class="token keyword">override</span> <span class="token keyword">init</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> <span class="token builtin">String</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">self</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><p>この場合はイニシャライザ内で<code>super.init()</code>を実行しなければいけません。</p>
<h2 id="マイグレーションのタイミング" tabindex="-1"><a class="header-anchor" href="#マイグレーションのタイミング" aria-hidden="true">#</a> マイグレーションのタイミング</h2>
<p>データベースのマイグレーションおよびスキームバージョンのアップデートは起動時に行われるべきです。</p>
<p>ただし、いくつかの注意点があります。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">SwiftUI</span>
<span class="token keyword">import</span> <span class="token builtin">Realm</span>
<span class="token keyword">import</span> <span class="token builtin">RealmSwift</span>

<span class="token comment">// グローバル変数で定義してはいけない</span>
<span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">!</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

@main
<span class="token keyword">struct</span> <span class="token builtin">RealmSwiftDemoApp</span><span class="token punctuation">:</span> <span class="token builtin">SwiftUI</span><span class="token punctuation">.</span><span class="token builtin">App</span> <span class="token punctuation">{</span>
    @<span class="token function">UIApplicationDelegateAdaptor</span><span class="token punctuation">(</span><span class="token builtin">AppDelegate</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span> <span class="token keyword">var</span> appDelegate

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">Scene</span> <span class="token punctuation">{</span>
        <span class="token builtin">WindowGroup</span> <span class="token punctuation">{</span>
            <span class="token function">ContentView</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">class</span> <span class="token class-name">AppDelegate</span><span class="token punctuation">:</span> <span class="token builtin">NSObject</span><span class="token punctuation">,</span> <span class="token builtin">UIApplicationDelegate</span> <span class="token punctuation">{</span>
    <span class="token keyword">func</span> <span class="token function">application</span><span class="token punctuation">(</span><span class="token number">_</span> application<span class="token punctuation">:</span> <span class="token builtin">UIApplication</span><span class="token punctuation">,</span> didFinishLaunchingWithOptions launchOptions<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token builtin">UIApplication</span><span class="token punctuation">.</span><span class="token builtin">LaunchOptionsKey</span><span class="token punctuation">:</span> <span class="token builtin">Any</span><span class="token punctuation">]</span><span class="token operator">?</span> <span class="token operator">=</span> <span class="token constant">nil</span><span class="token punctuation">)</span> <span class="token operator">-</span><span class="token operator">></span> <span class="token builtin">Bool</span> <span class="token punctuation">{</span>

        #<span class="token keyword">if</span> <span class="token constant">DEBUG</span>
        <span class="token keyword">let</span> config <span class="token operator">=</span> <span class="token builtin">Realm</span><span class="token punctuation">.</span><span class="token function">Configuration</span><span class="token punctuation">(</span>schemaVersion<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">,</span> deleteRealmIfMigrationNeeded<span class="token punctuation">:</span> <span class="token boolean">true</span><span class="token punctuation">)</span>
        <span class="token builtin">Realm</span><span class="token punctuation">.</span><span class="token builtin">Configuration</span><span class="token punctuation">.</span>defaultConfiguration <span class="token operator">=</span> config
        #<span class="token keyword">else</span>
        <span class="token keyword">let</span> config <span class="token operator">=</span> <span class="token builtin">Realm</span><span class="token punctuation">.</span><span class="token function">Configuration</span><span class="token punctuation">(</span>schemaVersion<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">)</span>
        <span class="token builtin">Realm</span><span class="token punctuation">.</span><span class="token builtin">Configuration</span><span class="token punctuation">.</span>defaultConfiguration <span class="token operator">=</span> config
        #endif
        <span class="token keyword">return</span> <span class="token boolean">true</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br></div></div><p>このように<code>let realm = try! Realm()</code>をグローバルで宣言すると、どこからでも利用できて便利なのですが<code>Realm.Configuration</code>でスキームバージョンを上げるよりも前に初期化されてしまうのでクラッシュします。</p>
<p>というよりも、<code>realm</code>のインスタンスはグローバルにすべきではありません。</p>
<p>何故なら、こうするとありとあらゆるファイルからデータベースの更新が可能になってしまい、コードの追加等で意図しないタイミングでデータベースが更新されてしまうからです。</p>
<p>なので、データベースを更新する専用のクラスをつくるほうが無難です。</p>
<h3 id="データベース更新用のクラス" tabindex="-1"><a class="header-anchor" href="#データベース更新用のクラス" aria-hidden="true">#</a> データベース更新用のクラス</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">import</span> <span class="token builtin">Foundation</span>
<span class="token keyword">import</span> <span class="token builtin">RealmSwift</span>

<span class="token keyword">final</span> <span class="token keyword">class</span> <span class="token class-name">RealmManager</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">!</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">class</span> <span class="token class-name">Objects</span> <span class="token punctuation">{</span>
        <span class="token keyword">static</span> <span class="token keyword">var</span> users<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">User</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><p>というわけで以下のようなクラスをつくってみた。</p>
<h2 id="swiftui-から削除するとクラッシュする問題" tabindex="-1"><a class="header-anchor" href="#swiftui-から削除するとクラッシュする問題" aria-hidden="true">#</a> SwiftUI から削除するとクラッシュする問題</h2>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code>    @<span class="token builtin">State</span> <span class="token keyword">var</span> users <span class="token operator">=</span> <span class="token builtin">RealmManager</span><span class="token punctuation">.</span><span class="token builtin">Objects</span><span class="token punctuation">.</span>users

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token function">ForEach</span><span class="token punctuation">(</span>users<span class="token punctuation">)</span> <span class="token punctuation">{</span> user <span class="token keyword">in</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>user<span class="token punctuation">.</span>id<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">onDelete</span><span class="token punctuation">(</span>perform<span class="token punctuation">:</span> delete<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">delete</span><span class="token punctuation">(</span>offsets<span class="token punctuation">:</span> <span class="token builtin">IndexSet</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">?</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> index <span class="token operator">=</span> offsets<span class="token punctuation">.</span><span class="token builtin">first</span> <span class="token punctuation">{</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span>write <span class="token punctuation">{</span>
                realm<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span>users<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><p>で、例えばこんなコードを書いてみます。</p>
<div class="custom-container tip"><p class="custom-container-title">Realm のインスタンス</p>
<p>本来は<code>realm</code>を<code>delete()</code>内で宣言したくなかったのですが、わかりやすくするために書きました。</p>
</div>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>libc++abi.dylib: terminating with uncaught exception of <span class="token builtin class-name">type</span> NSException
*** Terminating app due to uncaught exception <span class="token string">'RLMException'</span>, reason: <span class="token string">'Index 8 is out of bounds (must be less than 7).'</span>
terminating with uncaught exception of <span class="token builtin class-name">type</span> NSException
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>このコードを実装すると、リストからデータを削除したときにクラッシュしてしまいます。というのも、データベースから削除されたにも関わらず、SwiftUI が<code>ForEach</code>ですでに削除されているインデックスにアクセスしようとしてしまうためです。</p>
<h3 id="observableobject-を利用した回避法" tabindex="-1"><a class="header-anchor" href="#observableobject-を利用した回避法" aria-hidden="true">#</a> ObservableObject を利用した回避法</h3>
<p>要するに直接 Realm のデータ<code>RealmSwift.Results</code>を削除しようとしたためにエラーが発生してしまうので<code>RealmSwift.Results</code>を<code>Array</code>に変換して、SwiftUI 側では<code>Array</code>を使って<code>List</code>を表示するようにします。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">class</span> <span class="token class-name">UserModel</span><span class="token punctuation">:</span> <span class="token builtin">ObservableObject</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> token<span class="token punctuation">:</span> <span class="token builtin">NotificationToken</span><span class="token operator">?</span>
    <span class="token keyword">private</span> <span class="token keyword">var</span> users<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token builtin">RealmManager</span><span class="token punctuation">.</span><span class="token builtin">Objects</span><span class="token punctuation">.</span>users
    @<span class="token builtin">Published</span> <span class="token keyword">var</span> usersModel<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token builtin">User</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>

    <span class="token keyword">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// RealmSwift.Results&lt;User>が更新されるとこのクロージャが実行される</span>
        <span class="token comment">// そしてuserModelの配列がアップデートされる</span>
        token <span class="token operator">=</span> users<span class="token punctuation">.</span>observe <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token keyword">weak</span> <span class="token keyword">self</span><span class="token punctuation">]</span> <span class="token number">_</span> <span class="token keyword">in</span>
            <span class="token keyword">self</span><span class="token operator">?</span><span class="token punctuation">.</span>usersModel <span class="token operator">=</span> <span class="token function">Array</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token operator">!</span><span class="token punctuation">.</span>users<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><p>という感じで、データベースが更新されるとその通知を受け取ってから<code>Array</code>を更新します。あとは SwiftUI が<code>Array</code>を参照してリストを表示するようにすれば良いので、</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">ObservedObject</span> <span class="token keyword">var</span> userModel <span class="token operator">=</span> <span class="token function">UserModel</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token function">ForEach</span><span class="token punctuation">(</span>userModel<span class="token punctuation">.</span>usersModel<span class="token punctuation">)</span> <span class="token punctuation">{</span> user <span class="token keyword">in</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>user<span class="token punctuation">.</span>id<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">onDelete</span><span class="token punctuation">(</span>perform<span class="token punctuation">:</span> delete<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">delete</span><span class="token punctuation">(</span>offsets<span class="token punctuation">:</span> <span class="token builtin">IndexSet</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">?</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
        <span class="token comment">// 削除されたArrayから、削除されるRealmSwiftl.Results&lt;User>を計算する</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> index <span class="token operator">=</span> offsets<span class="token punctuation">.</span><span class="token builtin">first</span><span class="token punctuation">,</span> <span class="token keyword">let</span> user <span class="token operator">=</span> realm<span class="token punctuation">.</span><span class="token function">objects</span><span class="token punctuation">(</span><span class="token builtin">User</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token string">"id=%@"</span><span class="token punctuation">,</span> userModel<span class="token punctuation">.</span>usersModel<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">.</span>id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token builtin">first</span> <span class="token punctuation">{</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span>write <span class="token punctuation">{</span>
                realm<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span>user<span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div><p>とすれば良いことになります。</p>
<h3 id="observableobject-を利用しない回避法" tabindex="-1"><a class="header-anchor" href="#observableobject-を利用しない回避法" aria-hidden="true">#</a> ObservableObject を利用しない回避法</h3>
<p>また、<code>ObserverdObject</code>を使わない場合は以下のように書けます。</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">var</span> users<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token builtin">User</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">Array</span><span class="token punctuation">(</span><span class="token builtin">RealmManager</span><span class="token punctuation">.</span><span class="token builtin">Objects</span><span class="token punctuation">.</span>users<span class="token punctuation">)</span>

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token function">ForEach</span><span class="token punctuation">(</span>users<span class="token punctuation">)</span> <span class="token punctuation">{</span> user <span class="token keyword">in</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>user<span class="token punctuation">.</span>id<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">onDelete</span><span class="token punctuation">(</span>perform<span class="token punctuation">:</span> delete<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">delete</span><span class="token punctuation">(</span>offsets<span class="token punctuation">:</span> <span class="token builtin">IndexSet</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">?</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> index <span class="token operator">=</span> offsets<span class="token punctuation">.</span><span class="token builtin">first</span> <span class="token punctuation">{</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span>write <span class="token punctuation">{</span>
                <span class="token comment">// ここの判定は曖昧なのでより厳密にしても良いかも</span>
                <span class="token comment">// データベースから削除</span>
                realm<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span>users<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token comment">// SwiftUIのリストから削除</span>
            users<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>atOffsets<span class="token punctuation">:</span> offsets<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br></div></div><h3 id="frozen-objects-を利用した回避法" tabindex="-1"><a class="header-anchor" href="#frozen-objects-を利用した回避法" aria-hidden="true">#</a> Frozen Objects を利用した回避法</h3>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token builtin">ContentView</span><span class="token punctuation">:</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    @<span class="token builtin">State</span> <span class="token keyword">private</span><span class="token punctuation">(</span><span class="token keyword">set</span><span class="token punctuation">)</span> <span class="token keyword">var</span> users<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token builtin">RealmManager</span><span class="token punctuation">.</span><span class="token builtin">Objects</span><span class="token punctuation">.</span>users
    @<span class="token builtin">State</span> <span class="token keyword">private</span><span class="token punctuation">(</span><span class="token keyword">set</span><span class="token punctuation">)</span> <span class="token keyword">var</span> freezedUsers<span class="token punctuation">:</span> <span class="token builtin">RealmSwift</span><span class="token punctuation">.</span><span class="token builtin">Results</span><span class="token operator">&lt;</span><span class="token builtin">User</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token builtin">RealmManager</span><span class="token punctuation">.</span><span class="token builtin">Objects</span><span class="token punctuation">.</span>users

    <span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
        <span class="token builtin">Form</span> <span class="token punctuation">{</span>
            <span class="token function">ForEach</span><span class="token punctuation">(</span>users<span class="token punctuation">)</span> <span class="token punctuation">{</span> user <span class="token keyword">in</span>
                <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>user<span class="token punctuation">.</span>id<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token punctuation">.</span><span class="token function">onDelete</span><span class="token punctuation">(</span>perform<span class="token punctuation">:</span> delete<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">private</span> <span class="token keyword">func</span> <span class="token function">delete</span><span class="token punctuation">(</span>offsets<span class="token punctuation">:</span> <span class="token builtin">IndexSet</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> realm <span class="token operator">=</span> <span class="token keyword">try</span><span class="token operator">?</span> <span class="token function">Realm</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">else</span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token keyword">let</span> index <span class="token operator">=</span> offsets<span class="token punctuation">.</span><span class="token builtin">first</span> <span class="token punctuation">{</span>
            <span class="token keyword">try</span><span class="token operator">?</span> realm<span class="token punctuation">.</span>write <span class="token punctuation">{</span>
                <span class="token comment">// ここの判定は曖昧なのでより厳密にしても良いかも</span>
                <span class="token comment">// データベースから削除</span>
                realm<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span>freezedUsers<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            <span class="token comment">// freezeでコピー</span>
            users <span class="token operator">=</span> freezedUsers<span class="token punctuation">.</span><span class="token function">freeze</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br></div></div><p>同じものを複数用意するというのが少々ダサいです。</p>
<p>個人的にはループのところで、</p>
<div class="language-swift ext-swift line-numbers-mode"><pre v-pre class="language-swift"><code><span class="token keyword">var</span> body<span class="token punctuation">:</span> <span class="token keyword">some</span> <span class="token builtin">View</span> <span class="token punctuation">{</span>
    <span class="token builtin">Form</span> <span class="token punctuation">{</span>
        <span class="token function">ForEach</span><span class="token punctuation">(</span>users<span class="token punctuation">.</span><span class="token function">freeze</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> user <span class="token keyword">in</span>
            <span class="token function">Text</span><span class="token punctuation">(</span><span class="token string">"<span class="token interpolation"><span class="token delimiter variable">\(</span>user<span class="token punctuation">.</span>id<span class="token delimiter variable">)</span></span>"</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
        <span class="token punctuation">.</span><span class="token function">onDelete</span><span class="token punctuation">(</span>perform<span class="token punctuation">:</span> delete<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><p>ができたら便利だと思うのですが、これをやると削除しても SwiftUI がリストをアップデートしてくれませんでした、残念。</p>
</template>
